/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#include "RtxDrvPrivate.h"

IMPLEMENT_PACKAGE(RtxDrv)



IMPLEMENT_CLASS(URtx);
FNativeEntry<URtx> URtx::StaticNativeMap[] = {
	MAP_NATIVE(TestFunc,0)
	{NULL,NULL}
};
LINK_NATIVES(URtx);
