/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#include "RtxDrvPrivate.h"

IMPLEMENT_PACKAGE(RtxDrv)



IMPLEMENT_CLASS(URtxInterface);
FNativeEntry<URtxInterface> URtxInterface::StaticNativeMap[] = {
	MAP_NATIVE(CreateLight,0)
	MAP_NATIVE(DestroyLight,0)
	MAP_NATIVE(DestroyAllLights,0)
	MAP_NATIVE(GetInstance,0)
	{NULL,NULL}
};
LINK_NATIVES(URtxInterface);

IMPLEMENT_CLASS(URtxLight);
FNativeEntry<URtxLight> URtxLight::StaticNativeMap[] = {
	MAP_NATIVE(Update,0)
	{NULL,NULL}
};
LINK_NATIVES(URtxLight);
