/*===========================================================================
	C++ class definitions exported from UnrealScript.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#ifndef WINDOW_NATIVE_DEFS
#define WINDOW_NATIVE_DEFS

#include "../../Core/Inc/Core.h"

#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef WINDOW_API
#define WINDOW_API DLL_IMPORT
LINK_LIB(Window)
#endif

class WINDOW_API UWindowManager : public UObject{
public:
	DECLARE_CLASS(UWindowManager,UObject,0,Window)
	NO_DEFAULT_CONSTRUCTOR(UWindowManager)
};

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

WINDOW_API void InitWindowing();

#endif // WINDOW_NATIVE_DEFS