/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#ifndef MOD_NATIVE_DEFS
#define MOD_NATIVE_DEFS

#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef MOD_API
#define MOD_API DLL_IMPORT
#endif



class MOD_API UFunctionOverride : public UObject
{
public:
    class UObject* TargetObject;
    class UObject* OverrideObject;
    class UFunction* TargetFunction;
    class UFunction* OverrideFunction;
    class UObject* CurrentSelf;
    void execInit(FFrame& Stack, void* Result);
    void execDeinit(FFrame& Stack, void* Result);
    DECLARE_CLASS(UFunctionOverride,UObject,0,Mod)
    Native OriginalNative;
    DWORD  OriginalFunctionFlags;

    void Deinit();

    // Overrides
    virtual void Destroy();
    DECLARE_NATIVES(UFunctionOverride)
};

struct MOD_API FMPPawnHudArmsShaderPair
{
    class UMaterial* Pawn;
    class UMaterial* HudArms;
};


class MOD_API USWRCFix : public UObject
{
public:
    TArrayNoInit<FMPPawnHudArmsShaderPair> MPCloneHudArmsShaders;
    TArrayNoInit<FMPPawnHudArmsShaderPair> MPTrandoHudArmsShaders;
    FLOAT ViewShake;
    FLOAT BaseFOV;
    FLOAT FpsLimit;
    FLOAT FOV;
    FLOAT HudArmsFOVFactor;
    BITFIELD OverrideDefaultFOV:1 GCC_PACK(4);
    BITFIELD LimitHudArmsFOV:1;
    BITFIELD AutoFOV:1;
    BITFIELD EnableCustomMenu:1;
    BITFIELD EnableEditorSelectionFix:1;
    BITFIELD DisableWindowPositionVerification:1;
    class UFunctionOverride* CTPlayerEndZoomOverride GCC_PACK(4);
    class UFunctionOverride* CTPlayerResetFOVOverride;
    class UFunctionOverride* PlayerControllerShakeViewOverride;
    class UFunctionOverride* WeaponSetWeapFOVOverride;
    class UFunctionOverride* MenuBaseCallMenuClassOverride;
    class UFunctionOverride* MenuBaseOverlayMenuClassOverride;
    class UFunctionOverride* MenuBaseGotoMenuClassOverride;
    class UFunctionOverride* MPPawnSetHudArmTextureOverride;
    void InitScript()
    {
        DECLARE_NAME(InitScript);
        ProcessEvent(NInitScript, NULL);
    }
    FLOAT GetDefaultFOV()
    {
        DECLARE_NAME(GetDefaultFOV);
        struct {
            FLOAT ReturnValue;
        } Parms;
        Parms.ReturnValue=0;
        ProcessEvent(NGetDefaultFOV, &Parms);
        return Parms.ReturnValue;
    }
    void SetFOV(class APlayerController* Player, FLOAT NewFOV)
    {
        DECLARE_NAME(SetFOV);
        struct {
            class APlayerController* Player;
            FLOAT NewFOV;
        } Parms;
        Parms.Player=Player;
        Parms.NewFOV=NewFOV;
        ProcessEvent(NSetFOV, &Parms);
    }
    DECLARE_CLASS(USWRCFix,UObject,0|CLASS_Transient|CLASS_Config,Mod)
    void Init();

    static USWRCFix* Instance;
    static UBOOL     RenderingReady; // Used by ModRenderDevice to only render once everything is started up. This avoids loading tons of textures for no reason.
};



#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#if __STATIC_LINK

#define AUTO_INITIALIZE_REGISTRANTS_MOD \
	UExportBumpMapsCommandlet::StaticClass(); \
	UFunctionOverride::StaticClass(); \
	UModRenderDevice::StaticClass(); \
	USWRCFix::StaticClass(); \

#endif // __STATIC_LINK

#endif // CORE_NATIVE_DEFS
