/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#ifndef MOD_NATIVE_DEFS
#define MOD_NATIVE_DEFS

#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef MOD_API
#define MOD_API DLL_IMPORT
#endif



class MOD_API UFunctionOverride : public UObject
{
public:
    class UObject* TargetObject;
    class UObject* OverrideObject;
    class UFunction* TargetFunction;
    class UFunction* OverrideFunction;
    void execInit(FFrame& Stack, void* Result);
    void execDeinit(FFrame& Stack, void* Result);
    DECLARE_CLASS(UFunctionOverride,UObject,0,Mod)
	Native OriginalNative;
	DWORD  OriginalFunctionFlags;

	void Deinit();

	// Overrides
	virtual void Destroy();
    DECLARE_NATIVES(UFunctionOverride)
};



#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#if __STATIC_LINK

#define AUTO_INITIALIZE_REGISTRANTS_MOD \
	UFunctionOverride::StaticClass(); \

#endif // __STATIC_LINK

#endif // CORE_NATIVE_DEFS
