/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#include "ModPrivate.h"

IMPLEMENT_PACKAGE(Mod)



IMPLEMENT_CLASS(UModGameEngine);
