/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#ifndef RTXDRV_NATIVE_DEFS
#define RTXDRV_NATIVE_DEFS

#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef RTXDRV_API
#define RTXDRV_API DLL_IMPORT
#endif



class RTXDRV_API URtx : public UObject
{
public:
    void execTestFunc(FFrame& Stack, void* Result);
    DECLARE_CLASS(URtx,UObject,0,RtxDrv)
    NO_DEFAULT_CONSTRUCTOR(URtx)
    DECLARE_NATIVES(URtx)
};



#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#if __STATIC_LINK

#define AUTO_INITIALIZE_REGISTRANTS_RTXDRV \
	UConstantColorMaterial::StaticClass(); \
	URtx::StaticClass(); \
	URtxRenderDevice::StaticClass(); \

#endif // __STATIC_LINK

#endif // CORE_NATIVE_DEFS
