/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#include "ModMPGamePrivate.h"

IMPLEMENT_PACKAGE(ModMPGame)



IMPLEMENT_CLASS(ABotSupport);
