	// Events
	void TurretFire();
	void LoadAttachment();
	void HolsterAttachment();
	UBOOL IsTargeting();
	UBOOL IsTargetLocked();
	FLOAT GetTargetLockTime();
	FLOAT GetElapsedTargetLockTime();
	class UTexture* GetLockReticle();
	UBOOL IsSecondaryTargetLocked();
	FLOAT GetSecondaryTargetLockTime();
	FLOAT GetElapsedSecondaryTargetLockTime();
	void ServerFire();
	void StopFire(FLOAT Value);
	void ServerStopFire();
	FVector GetFireStart(const FVector& X, const FVector& Y, const FVector& Z);
	void ForceReload();
	void ServerForceReload();
	void ServerThrowGrenade();
	void ReleaseGrenade();
	void DoMeleeAttack();
	UBOOL CanSwitchWeapon();
	FLOAT SwitchPriority();
