/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2011 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations

// extern void *GMalloc; weak
// extern void *GError; weak
// extern void *GNatives; weak
// extern void *FName::Names; weak
// extern void *UObject::PrivateStaticClass; weak
// extern void *UObject::StaticConstructor; weak
// extern void *GEngine; weak
// extern void *AActor::PrivateStaticClass; weak
// extern void *AAIScript::PrivateStaticClass; weak
extern char aGameplay[9]; // weak
extern int (__thiscall *AScriptedController::_vftable_)(void *, char); // weak
extern char aInitactionfor[14]; // weak
extern char aGetactionactor[15]; // weak
extern int (__thiscall *UScriptedAction::_vftable_)(void *, char); // weak
extern int (__thiscall *UACTION_EnableAIVoice::_vftable_)(void *, char); // weak
extern int (__thiscall *UACTION_SetViewTarget::_vftable_)(void *, char); // weak
extern int (__thiscall *UACTION_TriggerEvent::_vftable_)(void *, char); // weak
extern int (__thiscall *ULatentScriptedAction::_vftable_)(void *, char); // weak
extern int (__thiscall *UACTION_TeleportToPoint::_vftable_)(void *, char); // weak
extern int (__thiscall *UACTION_WaitForEvent::_vftable_)(void *, char); // weak
extern char aS[3]; // weak
extern char aBdisabled[10]; // weak
extern __int16 word_100059C0; // weak
extern char byte_100059C2; // weak
extern char aAction_[8]; // weak
extern char asc_100059CC[4]; // weak
extern int (__thiscall *AScriptedSequence::_vftable_)(void *, char); // weak
extern char aScriptedsequen[17]; // weak
extern char aScriptedcontro[19]; // weak
extern char aScriptedaction[15]; // weak
extern char aAction_enablea[21]; // weak
extern char aAction_setview[21]; // weak
extern char aAction_trigger[20]; // weak
extern char aLatentscripted[21]; // weak
extern char aAction_telepor[23]; // weak
extern char aAction_waitfor[20]; // weak
extern _UNKNOWN unk_10005E00; // weak
extern _UNKNOWN unk_10005E08; // weak
extern _UNKNOWN unk_10006020; // weak
extern char *off_1000B088; // weak
extern char *UACTION_EnableAIVoice::StaticNativeMap; // weak
extern int NInitActionFor; // weak
extern int _local_static_guard_; // weak
extern int NGetActionActor; // weak
extern int _local_static_guard_; // weak
extern int dword_1000B0E0; // weak
extern int dword_1000B0E4; // weak
extern int dword_1000B0E8; // weak
extern int autoclassUScriptedAction; // weak
extern _UNKNOWN UACTION_TeleportToPoint::PrivateStaticClass; // weak
extern int autoclassUACTION_SetViewTarget; // weak
extern int autoclassAScriptedSequence; // weak
extern int autoclassULatentScriptedAction; // weak
extern _UNKNOWN UScriptedAction::PrivateStaticClass; // weak
extern _UNKNOWN UACTION_SetViewTarget::PrivateStaticClass; // weak
extern _UNKNOWN ULatentScriptedAction::PrivateStaticClass; // weak
extern int autoclassUACTION_TriggerEvent; // weak
extern _UNKNOWN AScriptedSequence::PrivateStaticClass; // weak
extern _UNKNOWN AScriptedController::PrivateStaticClass; // weak
extern _UNKNOWN UACTION_EnableAIVoice::PrivateStaticClass; // weak
extern int dword_1000B88C; // weak
extern int autoclassUACTION_TeleportToPoint; // weak
extern int autoclassUACTION_EnableAIVoice; // weak
extern int autoclassUACTION_WaitForEvent; // weak
extern _UNKNOWN UACTION_WaitForEvent::PrivateStaticClass; // weak
extern _UNKNOWN UACTION_TriggerEvent::PrivateStaticClass; // weak
extern int autoclassAScriptedController; // weak

//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int __cdecl sub_10001080(int a1);
_UNKNOWN *__cdecl AScriptedSequence::StaticClass();
int __cdecl AScriptedSequence::StaticPackageName();
int __stdcall AScriptedSequence::operator new(int a1, int a2);
int __fastcall AScriptedSequence::operator new(int a1, int a2);
_UNKNOWN *__cdecl AScriptedController::StaticClass();
int __cdecl AScriptedController::StaticPackageName();
int __stdcall AScriptedController::operator new(int a1, int a2);
int __fastcall AScriptedController::operator new(int a1, int a2);
int __thiscall AScriptedController::_AScriptedController(void *this);
void *__thiscall AScriptedController::AScriptedController(void *this);
void *__thiscall AScriptedController::AScriptedController(void *this, int a2);
void *__thiscall AScriptedController::operator_(void *this, int a2);
int __thiscall sub_10001440(void *, char); // idb
int __thiscall UScriptedAction::InitActionFor(void *this, int a2);
int __thiscall UScriptedAction::GetActionActor(void *this);
_UNKNOWN *__cdecl UScriptedAction::StaticClass();
int __cdecl UScriptedAction::StaticPackageName();
int __stdcall UScriptedAction::operator new(int a1, int a2);
int __fastcall UScriptedAction::operator new(int a1, int a2);
int __thiscall UScriptedAction::_UScriptedAction(void *this);
void *__thiscall UScriptedAction::UScriptedAction(void *this);
void *__thiscall UScriptedAction::UScriptedAction(void *this, int a2);
void *__thiscall UScriptedAction::operator_(void *this, int a2);
int __thiscall sub_10001820(void *, char); // idb
_UNKNOWN *__cdecl UACTION_EnableAIVoice::StaticClass();
int __cdecl UACTION_EnableAIVoice::StaticPackageName();
int __stdcall UACTION_EnableAIVoice::operator new(int a1, int a2);
int __fastcall UACTION_EnableAIVoice::operator new(int a1, int a2);
int __thiscall UACTION_EnableAIVoice::_UACTION_EnableAIVoice(void *this);
void *__thiscall UACTION_EnableAIVoice::UACTION_EnableAIVoice(void *this);
void *__thiscall UACTION_EnableAIVoice::UACTION_EnableAIVoice(void *this, int a2);
void *__thiscall UACTION_EnableAIVoice::operator_(void *this, int a2);
int __thiscall sub_100019E0(void *, char); // idb
_UNKNOWN *__cdecl UACTION_SetViewTarget::StaticClass();
int __cdecl UACTION_SetViewTarget::StaticPackageName();
int __stdcall UACTION_SetViewTarget::operator new(int a1, int a2);
int __fastcall UACTION_SetViewTarget::operator new(int a1, int a2);
int __thiscall UACTION_SetViewTarget::_UACTION_SetViewTarget(void *this);
void *__thiscall UACTION_SetViewTarget::UACTION_SetViewTarget(void *this);
void *__thiscall UACTION_SetViewTarget::UACTION_SetViewTarget(void *this, int a2);
void *__thiscall UACTION_SetViewTarget::operator_(void *this, int a2);
int __thiscall sub_10001B90(void *, char); // idb
_UNKNOWN *__cdecl UACTION_TriggerEvent::StaticClass();
int __cdecl UACTION_TriggerEvent::StaticPackageName();
int __stdcall UACTION_TriggerEvent::operator new(int a1, int a2);
int __fastcall UACTION_TriggerEvent::operator new(int a1, int a2);
int __thiscall UACTION_TriggerEvent::_UACTION_TriggerEvent(void *this);
void *__thiscall UACTION_TriggerEvent::UACTION_TriggerEvent(void *this);
void *__thiscall UACTION_TriggerEvent::UACTION_TriggerEvent(void *this, int a2);
void *__thiscall UACTION_TriggerEvent::operator_(void *this, int a2);
int __thiscall sub_10001D40(void *, char); // idb
_UNKNOWN *__cdecl ULatentScriptedAction::StaticClass();
int __cdecl ULatentScriptedAction::StaticPackageName();
int __stdcall ULatentScriptedAction::operator new(int a1, int a2);
int __fastcall ULatentScriptedAction::operator new(int a1, int a2);
int __thiscall ULatentScriptedAction::_ULatentScriptedAction(void *this);
void *__thiscall ULatentScriptedAction::ULatentScriptedAction(void *this);
void *__thiscall ULatentScriptedAction::ULatentScriptedAction(void *this, int a2);
void *__thiscall ULatentScriptedAction::operator_(void *this, int a2);
int __thiscall sub_10001EE0(void *, char); // idb
_UNKNOWN *__cdecl UACTION_TeleportToPoint::StaticClass();
int __cdecl UACTION_TeleportToPoint::StaticPackageName();
int __stdcall UACTION_TeleportToPoint::operator new(int a1, int a2);
int __fastcall UACTION_TeleportToPoint::operator new(int a1, int a2);
int __thiscall UACTION_TeleportToPoint::_UACTION_TeleportToPoint(void *this);
void *__thiscall UACTION_TeleportToPoint::UACTION_TeleportToPoint(void *this);
void *__thiscall UACTION_TeleportToPoint::UACTION_TeleportToPoint(void *this, int a2);
void *__thiscall UACTION_TeleportToPoint::operator_(void *this, int a2);
int __thiscall sub_100020E0(void *, char); // idb
_UNKNOWN *__cdecl UACTION_WaitForEvent::StaticClass();
int __cdecl UACTION_WaitForEvent::StaticPackageName();
int __stdcall UACTION_WaitForEvent::operator new(int a1, int a2);
int __fastcall UACTION_WaitForEvent::operator new(int a1, int a2);
int __thiscall UACTION_WaitForEvent::_UACTION_WaitForEvent(void *this);
void *__thiscall UACTION_WaitForEvent::UACTION_WaitForEvent(void *this);
void *__thiscall UACTION_WaitForEvent::UACTION_WaitForEvent(void *this, int a2);
void *__thiscall UACTION_WaitForEvent::operator_(void *this, int a2);
int __thiscall sub_100022C0(void *, char); // idb
int __thiscall UACTION_EnableAIVoice::execInitActionFor(void *this, int a2, int a3);
void *__thiscall AScriptedController::InternalConstructor(void *this);
void *__thiscall UScriptedAction::InternalConstructor(void *this);
void *__thiscall UACTION_EnableAIVoice::InternalConstructor(void *this);
void *__thiscall UACTION_SetViewTarget::InternalConstructor(void *this);
void *__thiscall UACTION_TriggerEvent::InternalConstructor(void *this);
void *__thiscall ULatentScriptedAction::InternalConstructor(void *this);
void *__thiscall UACTION_TeleportToPoint::InternalConstructor(void *this);
void *__thiscall UACTION_WaitForEvent::InternalConstructor(void *this);
char __thiscall AScriptedSequence::RenderEditorSelected(void *this, int a2, int a3, int a4);
void *__thiscall sub_10002860(void *this, int a2);
int __thiscall sub_10002940(int this, int a2, int a3);
int __thiscall sub_10002AB0(int this, int a2, int a3);
// void __usercall sub_10002B39(int a1<ebp>);
void __cdecl sub_10002B4D();
int __thiscall UScriptedAction::GetDescription(void *this, int a2);
int __thiscall sub_10002E10(int this, int a2);
int __thiscall sub_10002E60(int this, int a2, int a3);
int __thiscall AScriptedSequence::_AScriptedSequence(void *this);
void *__thiscall AScriptedSequence::AScriptedSequence(void *this);
int __thiscall sub_10002FC0(void *, char); // idb
void *__thiscall AScriptedSequence::InternalConstructor(void *this);
int __thiscall sub_10003040(int this, int a2);
void *__thiscall AScriptedSequence::operator_(void *this, int a2);
void *__thiscall AScriptedSequence::AScriptedSequence(void *this, int a2);
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
// int _CxxFrameHandler(void); weak
// int __stdcall unknown_libname_1(void *, unsigned int, int, void (__thiscall *)(void *)); idb
// int __cdecl CxxThrowException(_DWORD, _DWORD); weak
// int __cdecl atexit(void (__cdecl *)());
void __cdecl sub_10003A4E();
void __cdecl sub_10003A92(); // idb
// int __usercall sub_10003AF0<eax>(int a1<ebp>);
int __cdecl AScriptedController::_AScriptedController();
int __cdecl sub_10003B10();
int __cdecl UScriptedAction::InitActionFor();
int __cdecl sub_10003B30();
int __cdecl UScriptedAction::GetActionActor();
// int __usercall sub_10003B50<eax>(int a1<ebp>);
// int __usercall sub_10003B59<eax>(int a1<ebp>);
// int __usercall sub_10003B65<eax>(int a1<ebp>);
int __cdecl UScriptedAction::_UScriptedAction();
// int __usercall sub_10003B80<eax>(int a1<ebp>);
// int __usercall sub_10003B89<eax>(int a1<ebp>);
int __cdecl UScriptedAction::UScriptedAction();
// int __usercall sub_10003BA0<eax>(int a1<ebp>);
// int __usercall sub_10003BA9<eax>(int a1<ebp>);
int __cdecl UScriptedAction::UScriptedAction();
// int __usercall sub_10003BC0<eax>(int a1<ebp>);
int __cdecl UACTION_EnableAIVoice::_UACTION_EnableAIVoice();
// int __usercall sub_10003BE0<eax>(int a1<ebp>);
int __cdecl UACTION_SetViewTarget::_UACTION_SetViewTarget();
// int __usercall sub_10003C00<eax>(int a1<ebp>);
int __cdecl UACTION_TriggerEvent::_UACTION_TriggerEvent();
// int __usercall sub_10003C20<eax>(int a1<ebp>);
int __cdecl ULatentScriptedAction::_ULatentScriptedAction();
// int __usercall sub_10003C40<eax>(int a1<ebp>);
int __cdecl UACTION_TeleportToPoint::_UACTION_TeleportToPoint();
// int __usercall sub_10003C60<eax>(int a1<ebp>);
int __cdecl UACTION_WaitForEvent::_UACTION_WaitForEvent();
// int __usercall sub_10003C80<eax>(int a1<ebp>);
int __cdecl AScriptedSequence::RenderEditorSelected();
int __cdecl SEH_10002940();
int __cdecl SEH_10002AB0();
// int __usercall sub_10003CC0<eax>(int a1<ebp>);
int __cdecl sub_10003CCC();
// int __usercall sub_10003CDA<eax>(int a1<ebp>);
int __cdecl UScriptedAction::GetDescription();
// int __usercall sub_10003D10<eax>(int a1<ebp>);
// int __usercall sub_10003D19<eax>(int a1<ebp>);
int __cdecl AScriptedSequence::_AScriptedSequence();
// int __usercall sub_10003D40<eax>(int a1<ebp>);
int __cdecl AScriptedSequence::AScriptedSequence();
int __cdecl sub_10003D60(int a1, int a2);
void __cdecl sub_10003DF0();
int __cdecl sub_10003E00(int a1, int a2);
void __cdecl sub_10003E90();
int __cdecl sub_10003EA0(int a1, int a2);
void __cdecl sub_10003F20();
int __cdecl sub_10003F30(int a1, int a2);
void __cdecl sub_10003FB0();
int __cdecl sub_10003FC0();
int __cdecl sub_10003FE0(int a1, int a2);
void __cdecl sub_10004060();
int __cdecl sub_10004070(int a1, int a2);
void __cdecl sub_100040F0();
int __cdecl sub_10004100(int a1, int a2);
void __cdecl sub_10004180();
int __cdecl sub_10004190(int a1, int a2);
void __cdecl sub_10004210();
int __cdecl sub_10004220(int a1, int a2);
void __cdecl sub_100042A0();
int __cdecl sub_100042B0();
int __cdecl sub_100042C0();
int __cdecl sub_100042D0();
int __cdecl sub_100042E0();
int __cdecl sub_100042F0();
int __cdecl sub_10004300();
int __cdecl sub_10004310();
int __cdecl sub_10004320();
int __cdecl sub_10004330();
// int __thiscall UObject::StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int UObject::ConditionalDestroy(void); weak
// int __fastcall UObject::operator delete(_DWORD, _DWORD); weak
// int __thiscall UObject::ProcessEvent(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __thiscall FName::FName(_DWORD, _DWORD, _DWORD); weak
// int __thiscall UObject::_UObject(_DWORD); weak
// int __thiscall FStringNoInit::_FStringNoInit(_DWORD); weak
// int __thiscall FStringNoInit::FStringNoInit(_DWORD); weak
// int UObject::UObject(void); weak
// int __thiscall FStringNoInit::FStringNoInit(_DWORD, _DWORD); weak
// int __stdcall UObject::UObject(_DWORD); weak
// int __thiscall FStringNoInit::operator_(_DWORD, _DWORD); weak
// int __stdcall UObject::operator_(_DWORD); weak
// void appUnwindf(const char *, ...); weak
// int __thiscall FString::_FString(_DWORD); weak
// int __thiscall FString::FString(_DWORD, _DWORD); weak
// int __thiscall FString::operator__(_DWORD, _DWORD); weak
// int __fastcall appStrnicmp(const char *, const char *, int); weak
// int __thiscall FString::operator_(_DWORD, _DWORD); weak
// int __thiscall FString::FString(_DWORD); weak
// int __thiscall UClass::RegisterNatives(_DWORD); weak
// int __thiscall UClass::UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall UObject::StaticConfigName(_DWORD, _DWORD, _DWORD); weak
// int __thiscall UClass::_UClass(_DWORD); weak
// int __stdcall AActor::RenderEditorSelected(_DWORD, _DWORD, _DWORD); weak
// int __thiscall AAIController::_AAIController(_DWORD); weak
// int AAIController::AAIController(void); weak
// int __stdcall AAIController::AAIController(_DWORD); weak
// int __stdcall AAIController::operator_(_DWORD); weak
// int __stdcall UAudioSubsystem::DisableVoiceCuesManually(_DWORD); weak
// int __thiscall FLineBatcher::_FLineBatcher(_DWORD); weak
// int __thiscall FLineBatcher::DrawLine(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __thiscall FLineBatcher::FLineBatcher(_DWORD, _DWORD, _DWORD); weak
// int __thiscall AAIScript::_AAIScript(_DWORD); weak
// int AAIScript::AAIScript(void); weak
// int __stdcall AAIScript::operator_(_DWORD); weak
// int __stdcall AAIScript::AAIScript(_DWORD); weak
// void *__cdecl memmove(void *Dst, const void *Src, size_t Size);


//----- (10001080) --------------------------------------------------------
int __cdecl sub_10001080(int a1)
{
  return (*(int (__stdcall **)(int))(*(_DWORD *)GMalloc + 12))(a1);
}
// 10005000: using guessed type void *GMalloc;

//----- (100010F0) --------------------------------------------------------
_UNKNOWN *__cdecl AScriptedSequence::StaticClass()
{
  return &AScriptedSequence::PrivateStaticClass;
}

//----- (10001100) --------------------------------------------------------
int __cdecl AScriptedSequence::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (10001110) --------------------------------------------------------
int __stdcall AScriptedSequence::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&AScriptedSequence::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (10001140) --------------------------------------------------------
int __fastcall AScriptedSequence::operator new(int a1, int a2)
{
  return a2;
}

//----- (10001150) --------------------------------------------------------
_UNKNOWN *__cdecl AScriptedController::StaticClass()
{
  return &AScriptedController::PrivateStaticClass;
}

//----- (10001160) --------------------------------------------------------
int __cdecl AScriptedController::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (10001170) --------------------------------------------------------
int __stdcall AScriptedController::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&AScriptedController::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (100011A0) --------------------------------------------------------
int __fastcall AScriptedController::operator new(int a1, int a2)
{
  return a2;
}

//----- (100011B0) --------------------------------------------------------
int __thiscall AScriptedController::_AScriptedController(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &AScriptedController::_vftable_;
  UObject::ConditionalDestroy();
  return AAIController::_AAIController(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 100052E8: using guessed type int __thiscall AAIController___AAIController(_DWORD);
// 100053C8: using guessed type int (__thiscall *AScriptedController___vftable_)(void *, char);

//----- (10001210) --------------------------------------------------------
void *__thiscall AScriptedController::AScriptedController(void *this)
{
  void *v1; // esi@1

  v1 = this;
  AAIController::AAIController();
  *(_DWORD *)v1 = &AScriptedController::_vftable_;
  return v1;
}
// 100052EC: using guessed type int AAIController__AAIController(void);
// 100053C8: using guessed type int (__thiscall *AScriptedController___vftable_)(void *, char);

//----- (10001230) --------------------------------------------------------
void *__thiscall AScriptedController::AScriptedController(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // eax@1
  int v4; // ecx@1
  int v5; // eax@1

  v2 = this;
  AAIController::AAIController(a2);
  v3 = *((_DWORD *)v2 + 217);
  *(_DWORD *)v2 = &AScriptedController::_vftable_;
  v4 = (*(_DWORD *)(a2 + 868) ^ v3) & 1 ^ *((_DWORD *)v2 + 217);
  *((_DWORD *)v2 + 217) = v4;
  v5 = v4 ^ ((unsigned __int8)v4 ^ (unsigned __int8)*(_DWORD *)(a2 + 868)) & 2;
  *((_DWORD *)v2 + 217) = v5;
  *((_DWORD *)v2 + 217) = v5 ^ ((unsigned __int8)v5 ^ (unsigned __int8)*(_DWORD *)(a2 + 868)) & 4;
  *((_DWORD *)v2 + 218) = *(_DWORD *)(a2 + 872);
  *((_DWORD *)v2 + 219) = *(_DWORD *)(a2 + 876);
  *((_DWORD *)v2 + 220) = *(_DWORD *)(a2 + 880);
  *((_DWORD *)v2 + 221) = *(_DWORD *)(a2 + 884);
  *((_DWORD *)v2 + 222) = *(_DWORD *)(a2 + 888);
  *((_DWORD *)v2 + 223) = *(_DWORD *)(a2 + 892);
  *((_DWORD *)v2 + 224) = *(_DWORD *)(a2 + 896);
  *((_DWORD *)v2 + 225) = *(_DWORD *)(a2 + 900);
  *((_DWORD *)v2 + 226) = *(_DWORD *)(a2 + 904);
  *((_DWORD *)v2 + 227) = *(_DWORD *)(a2 + 908);
  *((_DWORD *)v2 + 228) = *(_DWORD *)(a2 + 912);
  *((_DWORD *)v2 + 229) = *(_DWORD *)(a2 + 916);
  return v2;
}
// 100052F0: using guessed type int __stdcall AAIController__AAIController(_DWORD);
// 100053C8: using guessed type int (__thiscall *AScriptedController___vftable_)(void *, char);

//----- (10001320) --------------------------------------------------------
void *__thiscall AScriptedController::operator_(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // ecx@1
  int v4; // eax@1

  v2 = this;
  AAIController::operator_(a2);
  v3 = ((unsigned __int8)*(_DWORD *)(a2 + 868) ^ (unsigned __int8)*((_DWORD *)v2 + 217)) & 1 ^ *((_DWORD *)v2 + 217);
  *((_DWORD *)v2 + 217) = v3;
  v4 = v3 ^ ((unsigned __int8)v3 ^ (unsigned __int8)*(_DWORD *)(a2 + 868)) & 2;
  *((_DWORD *)v2 + 217) = v4;
  *((_DWORD *)v2 + 217) = v4 ^ ((unsigned __int8)v4 ^ (unsigned __int8)*(_DWORD *)(a2 + 868)) & 4;
  *((_DWORD *)v2 + 218) = *(_DWORD *)(a2 + 872);
  *((_DWORD *)v2 + 219) = *(_DWORD *)(a2 + 876);
  *((_DWORD *)v2 + 220) = *(_DWORD *)(a2 + 880);
  *((_DWORD *)v2 + 221) = *(_DWORD *)(a2 + 884);
  *((_DWORD *)v2 + 222) = *(_DWORD *)(a2 + 888);
  *((_DWORD *)v2 + 223) = *(_DWORD *)(a2 + 892);
  *((_DWORD *)v2 + 224) = *(_DWORD *)(a2 + 896);
  *((_DWORD *)v2 + 225) = *(_DWORD *)(a2 + 900);
  *((_DWORD *)v2 + 226) = *(_DWORD *)(a2 + 904);
  *((_DWORD *)v2 + 227) = *(_DWORD *)(a2 + 908);
  *((_DWORD *)v2 + 228) = *(_DWORD *)(a2 + 912);
  *((_DWORD *)v2 + 229) = *(_DWORD *)(a2 + 916);
  return v2;
}
// 100052F4: using guessed type int __stdcall AAIController__operator_(_DWORD);

//----- (10001440) --------------------------------------------------------
int __thiscall sub_10001440(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x398u, *((_DWORD *)this - 1), AScriptedController::_AScriptedController);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    AScriptedController::_AScriptedController(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 920);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (100014A0) --------------------------------------------------------
int __thiscall UScriptedAction::InitActionFor(void *this, int a2)
{
  void *v2; // esi@1
  int v4; // [sp+10h] [bp-14h]@3
  int v5; // [sp+14h] [bp-10h]@3
  int v6; // [sp+20h] [bp-4h]@2

  v2 = this;
  if ( !(_local_static_guard_ & 1) )
  {
    _local_static_guard_ |= 1u;
    FName::FName(&NInitActionFor, "InitActionFor", 2);
    v6 = -1;
  }
  v4 = a2;
  v5 = 0;
  UObject::ProcessEvent(v2, NInitActionFor, &v4, 0);
  return v5;
}
// 10005048: using guessed type int __thiscall UObject__ProcessEvent(_DWORD, _DWORD, _DWORD, _DWORD);
// 1000504C: using guessed type int __thiscall FName__FName(_DWORD, _DWORD, _DWORD);
// 1000B0D0: using guessed type int NInitActionFor;
// 1000B0D4: using guessed type int _local static guard_;

//----- (10001530) --------------------------------------------------------
int __thiscall UScriptedAction::GetActionActor(void *this)
{
  void *v1; // esi@1
  int v3; // [sp+14h] [bp-10h]@3
  int v4; // [sp+20h] [bp-4h]@2

  v1 = this;
  if ( !(_local_static_guard_ & 1) )
  {
    _local_static_guard_ |= 1u;
    FName::FName(&NGetActionActor, "GetActionActor", 2);
    v4 = -1;
  }
  v3 = 0;
  UObject::ProcessEvent(v1, NGetActionActor, &v3, 0);
  return v3;
}
// 10005048: using guessed type int __thiscall UObject__ProcessEvent(_DWORD, _DWORD, _DWORD, _DWORD);
// 1000504C: using guessed type int __thiscall FName__FName(_DWORD, _DWORD, _DWORD);
// 1000B0D8: using guessed type int NGetActionActor;
// 1000B0DC: using guessed type int _local static guard_;

//----- (100015C0) --------------------------------------------------------
_UNKNOWN *__cdecl UScriptedAction::StaticClass()
{
  return &UScriptedAction::PrivateStaticClass;
}

//----- (100015D0) --------------------------------------------------------
int __cdecl UScriptedAction::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (100015E0) --------------------------------------------------------
int __stdcall UScriptedAction::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&UScriptedAction::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (10001610) --------------------------------------------------------
int __fastcall UScriptedAction::operator new(int a1, int a2)
{
  return a2;
}

//----- (10001620) --------------------------------------------------------
int __thiscall UScriptedAction::_UScriptedAction(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &UScriptedAction::_vftable_;
  UObject::ConditionalDestroy();
  FStringNoInit::_FStringNoInit((char *)v1 + 56);
  FStringNoInit::_FStringNoInit((char *)v1 + 40);
  return UObject::_UObject(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 1000508C: using guessed type int __thiscall UObject___UObject(_DWORD);
// 10005090: using guessed type int __thiscall FStringNoInit___FStringNoInit(_DWORD);
// 10005620: using guessed type int (__thiscall *UScriptedAction___vftable_)(void *, char);

//----- (10001690) --------------------------------------------------------
void *__thiscall UScriptedAction::UScriptedAction(void *this)
{
  void *v1; // esi@1

  v1 = this;
  UObject::UObject();
  *(_DWORD *)v1 = &UScriptedAction::_vftable_;
  FStringNoInit::FStringNoInit((char *)v1 + 40);
  FStringNoInit::FStringNoInit((char *)v1 + 56);
  return v1;
}
// 10005094: using guessed type int __thiscall FStringNoInit__FStringNoInit(_DWORD);
// 10005098: using guessed type int UObject__UObject(void);
// 10005620: using guessed type int (__thiscall *UScriptedAction___vftable_)(void *, char);

//----- (100016F0) --------------------------------------------------------
void *__thiscall UScriptedAction::UScriptedAction(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // edx@1

  v2 = this;
  UObject::UObject(a2);
  *(_DWORD *)v2 = &UScriptedAction::_vftable_;
  FStringNoInit::FStringNoInit((char *)v2 + 40, a2 + 40);
  v3 = ((unsigned __int8)*(_DWORD *)(a2 + 48) ^ (unsigned __int8)*((_DWORD *)v2 + 12)) & 1 ^ *((_DWORD *)v2 + 12);
  *((_DWORD *)v2 + 12) = v3;
  *((_DWORD *)v2 + 12) = v3 ^ ((unsigned __int8)v3 ^ (unsigned __int8)*(_DWORD *)(a2 + 48)) & 2;
  *((_DWORD *)v2 + 13) = *(_DWORD *)(a2 + 52);
  FStringNoInit::FStringNoInit((char *)v2 + 56, a2 + 56);
  return v2;
}
// 1000509C: using guessed type int __thiscall FStringNoInit__FStringNoInit(_DWORD, _DWORD);
// 100050A0: using guessed type int __stdcall UObject__UObject(_DWORD);
// 10005620: using guessed type int (__thiscall *UScriptedAction___vftable_)(void *, char);

//----- (10001790) --------------------------------------------------------
void *__thiscall UScriptedAction::operator_(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // edx@1

  v2 = this;
  UObject::operator_(a2);
  FStringNoInit::operator_((char *)v2 + 40, a2 + 40);
  v3 = ((unsigned __int8)*(_DWORD *)(a2 + 48) ^ (unsigned __int8)*((_DWORD *)v2 + 12)) & 1 ^ *((_DWORD *)v2 + 12);
  *((_DWORD *)v2 + 12) = v3;
  *((_DWORD *)v2 + 12) = v3 ^ ((unsigned __int8)v3 ^ (unsigned __int8)*(_DWORD *)(a2 + 48)) & 2;
  *((_DWORD *)v2 + 13) = *(_DWORD *)(a2 + 52);
  FStringNoInit::operator_((char *)v2 + 56, a2 + 56);
  return v2;
}
// 100050A4: using guessed type int __thiscall FStringNoInit__operator_(_DWORD, _DWORD);
// 100050A8: using guessed type int __stdcall UObject__operator_(_DWORD);

//----- (10001820) --------------------------------------------------------
int __thiscall sub_10001820(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x40u, *((_DWORD *)this - 1), UScriptedAction::_UScriptedAction);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    UScriptedAction::_UScriptedAction(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 64);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10001880) --------------------------------------------------------
_UNKNOWN *__cdecl UACTION_EnableAIVoice::StaticClass()
{
  return &UACTION_EnableAIVoice::PrivateStaticClass;
}

//----- (10001890) --------------------------------------------------------
int __cdecl UACTION_EnableAIVoice::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (100018A0) --------------------------------------------------------
int __stdcall UACTION_EnableAIVoice::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&UACTION_EnableAIVoice::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (100018D0) --------------------------------------------------------
int __fastcall UACTION_EnableAIVoice::operator new(int a1, int a2)
{
  return a2;
}

//----- (100018E0) --------------------------------------------------------
int __thiscall UACTION_EnableAIVoice::_UACTION_EnableAIVoice(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &UACTION_EnableAIVoice::_vftable_;
  UObject::ConditionalDestroy();
  return UScriptedAction::_UScriptedAction(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 10005698: using guessed type int (__thiscall *UACTION_EnableAIVoice___vftable_)(void *, char);

//----- (10001930) --------------------------------------------------------
void *__thiscall UACTION_EnableAIVoice::UACTION_EnableAIVoice(void *this)
{
  void *v1; // esi@1

  v1 = this;
  UScriptedAction::UScriptedAction(this);
  *(_DWORD *)v1 = &UACTION_EnableAIVoice::_vftable_;
  return v1;
}
// 10005698: using guessed type int (__thiscall *UACTION_EnableAIVoice___vftable_)(void *, char);

//----- (10001950) --------------------------------------------------------
void *__thiscall UACTION_EnableAIVoice::UACTION_EnableAIVoice(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::UScriptedAction(this, a2);
  *(_DWORD *)v2 = &UACTION_EnableAIVoice::_vftable_;
  *((_DWORD *)v2 + 16) ^= ((unsigned __int8)*((_DWORD *)v2 + 16) ^ (unsigned __int8)*(_DWORD *)(a2 + 64)) & 1;
  return v2;
}
// 10005698: using guessed type int (__thiscall *UACTION_EnableAIVoice___vftable_)(void *, char);

//----- (10001980) --------------------------------------------------------
void *__thiscall UACTION_EnableAIVoice::operator_(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::operator_(this, a2);
  *((_DWORD *)v2 + 16) ^= ((unsigned __int8)*((_DWORD *)v2 + 16) ^ (unsigned __int8)*(_DWORD *)(a2 + 64)) & 1;
  return v2;
}

//----- (100019E0) --------------------------------------------------------
int __thiscall sub_100019E0(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x44u, *((_DWORD *)this - 1), UACTION_EnableAIVoice::_UACTION_EnableAIVoice);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    UACTION_EnableAIVoice::_UACTION_EnableAIVoice(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 68);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10001A40) --------------------------------------------------------
_UNKNOWN *__cdecl UACTION_SetViewTarget::StaticClass()
{
  return &UACTION_SetViewTarget::PrivateStaticClass;
}

//----- (10001A50) --------------------------------------------------------
int __cdecl UACTION_SetViewTarget::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (10001A60) --------------------------------------------------------
int __stdcall UACTION_SetViewTarget::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&UACTION_SetViewTarget::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (10001A90) --------------------------------------------------------
int __fastcall UACTION_SetViewTarget::operator new(int a1, int a2)
{
  return a2;
}

//----- (10001AA0) --------------------------------------------------------
int __thiscall UACTION_SetViewTarget::_UACTION_SetViewTarget(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &UACTION_SetViewTarget::_vftable_;
  UObject::ConditionalDestroy();
  return UScriptedAction::_UScriptedAction(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 10005710: using guessed type int (__thiscall *UACTION_SetViewTarget___vftable_)(void *, char);

//----- (10001AF0) --------------------------------------------------------
void *__thiscall UACTION_SetViewTarget::UACTION_SetViewTarget(void *this)
{
  void *v1; // esi@1

  v1 = this;
  UScriptedAction::UScriptedAction(this);
  *(_DWORD *)v1 = &UACTION_SetViewTarget::_vftable_;
  return v1;
}
// 10005710: using guessed type int (__thiscall *UACTION_SetViewTarget___vftable_)(void *, char);

//----- (10001B10) --------------------------------------------------------
void *__thiscall UACTION_SetViewTarget::UACTION_SetViewTarget(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::UScriptedAction(this, a2);
  *(_DWORD *)v2 = &UACTION_SetViewTarget::_vftable_;
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  return v2;
}
// 10005710: using guessed type int (__thiscall *UACTION_SetViewTarget___vftable_)(void *, char);

//----- (10001B40) --------------------------------------------------------
void *__thiscall UACTION_SetViewTarget::operator_(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::operator_(this, a2);
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  return v2;
}

//----- (10001B90) --------------------------------------------------------
int __thiscall sub_10001B90(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x44u, *((_DWORD *)this - 1), UACTION_SetViewTarget::_UACTION_SetViewTarget);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    UACTION_SetViewTarget::_UACTION_SetViewTarget(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 68);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10001BF0) --------------------------------------------------------
_UNKNOWN *__cdecl UACTION_TriggerEvent::StaticClass()
{
  return &UACTION_TriggerEvent::PrivateStaticClass;
}

//----- (10001C00) --------------------------------------------------------
int __cdecl UACTION_TriggerEvent::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (10001C10) --------------------------------------------------------
int __stdcall UACTION_TriggerEvent::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&UACTION_TriggerEvent::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (10001C40) --------------------------------------------------------
int __fastcall UACTION_TriggerEvent::operator new(int a1, int a2)
{
  return a2;
}

//----- (10001C50) --------------------------------------------------------
int __thiscall UACTION_TriggerEvent::_UACTION_TriggerEvent(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &UACTION_TriggerEvent::_vftable_;
  UObject::ConditionalDestroy();
  return UScriptedAction::_UScriptedAction(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 10005788: using guessed type int (__thiscall *UACTION_TriggerEvent___vftable_)(void *, char);

//----- (10001CA0) --------------------------------------------------------
void *__thiscall UACTION_TriggerEvent::UACTION_TriggerEvent(void *this)
{
  void *v1; // esi@1

  v1 = this;
  UScriptedAction::UScriptedAction(this);
  *(_DWORD *)v1 = &UACTION_TriggerEvent::_vftable_;
  return v1;
}
// 10005788: using guessed type int (__thiscall *UACTION_TriggerEvent___vftable_)(void *, char);

//----- (10001CC0) --------------------------------------------------------
void *__thiscall UACTION_TriggerEvent::UACTION_TriggerEvent(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::UScriptedAction(this, a2);
  *(_DWORD *)v2 = &UACTION_TriggerEvent::_vftable_;
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  return v2;
}
// 10005788: using guessed type int (__thiscall *UACTION_TriggerEvent___vftable_)(void *, char);

//----- (10001CF0) --------------------------------------------------------
void *__thiscall UACTION_TriggerEvent::operator_(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::operator_(this, a2);
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  return v2;
}

//----- (10001D40) --------------------------------------------------------
int __thiscall sub_10001D40(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x44u, *((_DWORD *)this - 1), UACTION_TriggerEvent::_UACTION_TriggerEvent);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    UACTION_TriggerEvent::_UACTION_TriggerEvent(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 68);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10001DA0) --------------------------------------------------------
_UNKNOWN *__cdecl ULatentScriptedAction::StaticClass()
{
  return &ULatentScriptedAction::PrivateStaticClass;
}

//----- (10001DB0) --------------------------------------------------------
int __cdecl ULatentScriptedAction::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (10001DC0) --------------------------------------------------------
int __stdcall ULatentScriptedAction::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&ULatentScriptedAction::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (10001DF0) --------------------------------------------------------
int __fastcall ULatentScriptedAction::operator new(int a1, int a2)
{
  return a2;
}

//----- (10001E00) --------------------------------------------------------
int __thiscall ULatentScriptedAction::_ULatentScriptedAction(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &ULatentScriptedAction::_vftable_;
  UObject::ConditionalDestroy();
  return UScriptedAction::_UScriptedAction(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 10005800: using guessed type int (__thiscall *ULatentScriptedAction___vftable_)(void *, char);

//----- (10001E50) --------------------------------------------------------
void *__thiscall ULatentScriptedAction::ULatentScriptedAction(void *this)
{
  void *v1; // esi@1

  v1 = this;
  UScriptedAction::UScriptedAction(this);
  *(_DWORD *)v1 = &ULatentScriptedAction::_vftable_;
  return v1;
}
// 10005800: using guessed type int (__thiscall *ULatentScriptedAction___vftable_)(void *, char);

//----- (10001E70) --------------------------------------------------------
void *__thiscall ULatentScriptedAction::ULatentScriptedAction(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::UScriptedAction(this, a2);
  *(_DWORD *)v2 = &ULatentScriptedAction::_vftable_;
  return v2;
}
// 10005800: using guessed type int (__thiscall *ULatentScriptedAction___vftable_)(void *, char);

//----- (10001E90) --------------------------------------------------------
void *__thiscall ULatentScriptedAction::operator_(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::operator_(this, a2);
  return v2;
}

//----- (10001EE0) --------------------------------------------------------
int __thiscall sub_10001EE0(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x40u, *((_DWORD *)this - 1), ULatentScriptedAction::_ULatentScriptedAction);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    ULatentScriptedAction::_ULatentScriptedAction(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 64);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10001F40) --------------------------------------------------------
_UNKNOWN *__cdecl UACTION_TeleportToPoint::StaticClass()
{
  return &UACTION_TeleportToPoint::PrivateStaticClass;
}

//----- (10001F50) --------------------------------------------------------
int __cdecl UACTION_TeleportToPoint::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (10001F60) --------------------------------------------------------
int __stdcall UACTION_TeleportToPoint::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&UACTION_TeleportToPoint::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (10001F90) --------------------------------------------------------
int __fastcall UACTION_TeleportToPoint::operator new(int a1, int a2)
{
  return a2;
}

//----- (10001FA0) --------------------------------------------------------
int __thiscall UACTION_TeleportToPoint::_UACTION_TeleportToPoint(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &UACTION_TeleportToPoint::_vftable_;
  UObject::ConditionalDestroy();
  return ULatentScriptedAction::_ULatentScriptedAction(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 10005878: using guessed type int (__thiscall *UACTION_TeleportToPoint___vftable_)(void *, char);

//----- (10001FF0) --------------------------------------------------------
void *__thiscall UACTION_TeleportToPoint::UACTION_TeleportToPoint(void *this)
{
  void *v1; // esi@1

  v1 = this;
  UScriptedAction::UScriptedAction(this);
  *(_DWORD *)v1 = &UACTION_TeleportToPoint::_vftable_;
  return v1;
}
// 10005878: using guessed type int (__thiscall *UACTION_TeleportToPoint___vftable_)(void *, char);

//----- (10002010) --------------------------------------------------------
void *__thiscall UACTION_TeleportToPoint::UACTION_TeleportToPoint(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // edx@1
  int v4; // eax@1

  v2 = this;
  UScriptedAction::UScriptedAction(this, a2);
  v3 = *((_DWORD *)v2 + 18);
  *(_DWORD *)v2 = &UACTION_TeleportToPoint::_vftable_;
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  *((_DWORD *)v2 + 17) = *(_DWORD *)(a2 + 68);
  v4 = (*(_DWORD *)(a2 + 72) ^ v3) & 1 ^ *((_DWORD *)v2 + 18);
  *((_DWORD *)v2 + 18) = v4;
  *((_DWORD *)v2 + 18) = v4 ^ ((unsigned __int8)v4 ^ (unsigned __int8)*(_DWORD *)(a2 + 72)) & 2;
  *((_DWORD *)v2 + 19) = *(_DWORD *)(a2 + 76);
  return v2;
}
// 10005878: using guessed type int (__thiscall *UACTION_TeleportToPoint___vftable_)(void *, char);

//----- (10002060) --------------------------------------------------------
void *__thiscall UACTION_TeleportToPoint::operator_(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // edx@1
  int v4; // eax@1

  v2 = this;
  UScriptedAction::operator_(this, a2);
  v3 = *((_DWORD *)v2 + 18);
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  *((_DWORD *)v2 + 17) = *(_DWORD *)(a2 + 68);
  v4 = (*(_DWORD *)(a2 + 72) ^ v3) & 1 ^ *((_DWORD *)v2 + 18);
  *((_DWORD *)v2 + 18) = v4;
  *((_DWORD *)v2 + 18) = v4 ^ ((unsigned __int8)v4 ^ (unsigned __int8)*(_DWORD *)(a2 + 72)) & 2;
  *((_DWORD *)v2 + 19) = *(_DWORD *)(a2 + 76);
  return v2;
}

//----- (100020E0) --------------------------------------------------------
int __thiscall sub_100020E0(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x50u, *((_DWORD *)this - 1), UACTION_TeleportToPoint::_UACTION_TeleportToPoint);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    UACTION_TeleportToPoint::_UACTION_TeleportToPoint(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 80);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10002140) --------------------------------------------------------
_UNKNOWN *__cdecl UACTION_WaitForEvent::StaticClass()
{
  return &UACTION_WaitForEvent::PrivateStaticClass;
}

//----- (10002150) --------------------------------------------------------
int __cdecl UACTION_WaitForEvent::StaticPackageName()
{
  return (int)"Gameplay";
}

//----- (10002160) --------------------------------------------------------
int __stdcall UACTION_WaitForEvent::operator new(int a1, int a2)
{
  return UObject::StaticAllocateObject(&UACTION_WaitForEvent::PrivateStaticClass, a1, a2, 0, GError, 0, 0);
}
// 10005004: using guessed type int __thiscall UObject__StaticAllocateObject(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 10005008: using guessed type void *GError;

//----- (10002190) --------------------------------------------------------
int __fastcall UACTION_WaitForEvent::operator new(int a1, int a2)
{
  return a2;
}

//----- (100021A0) --------------------------------------------------------
int __thiscall UACTION_WaitForEvent::_UACTION_WaitForEvent(void *this)
{
  void *v1; // esi@1

  v1 = this;
  *(_DWORD *)this = &UACTION_WaitForEvent::_vftable_;
  UObject::ConditionalDestroy();
  return ULatentScriptedAction::_ULatentScriptedAction(v1);
}
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 100058F0: using guessed type int (__thiscall *UACTION_WaitForEvent___vftable_)(void *, char);

//----- (100021F0) --------------------------------------------------------
void *__thiscall UACTION_WaitForEvent::UACTION_WaitForEvent(void *this)
{
  void *v1; // esi@1

  v1 = this;
  UScriptedAction::UScriptedAction(this);
  *(_DWORD *)v1 = &UACTION_WaitForEvent::_vftable_;
  return v1;
}
// 100058F0: using guessed type int (__thiscall *UACTION_WaitForEvent___vftable_)(void *, char);

//----- (10002210) --------------------------------------------------------
void *__thiscall UACTION_WaitForEvent::UACTION_WaitForEvent(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::UScriptedAction(this, a2);
  *(_DWORD *)v2 = &UACTION_WaitForEvent::_vftable_;
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  *((_DWORD *)v2 + 17) = *(_DWORD *)(a2 + 68);
  *((_DWORD *)v2 + 18) = *(_DWORD *)(a2 + 72);
  *((_DWORD *)v2 + 19) ^= ((unsigned __int8)*((_DWORD *)v2 + 19) ^ (unsigned __int8)*(_DWORD *)(a2 + 76)) & 1;
  return v2;
}
// 100058F0: using guessed type int (__thiscall *UACTION_WaitForEvent___vftable_)(void *, char);

//----- (10002250) --------------------------------------------------------
void *__thiscall UACTION_WaitForEvent::operator_(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  UScriptedAction::operator_(this, a2);
  *((_DWORD *)v2 + 16) = *(_DWORD *)(a2 + 64);
  *((_DWORD *)v2 + 17) = *(_DWORD *)(a2 + 68);
  *((_DWORD *)v2 + 18) = *(_DWORD *)(a2 + 72);
  *((_DWORD *)v2 + 19) ^= ((unsigned __int8)*((_DWORD *)v2 + 19) ^ (unsigned __int8)*(_DWORD *)(a2 + 76)) & 1;
  return v2;
}

//----- (100022C0) --------------------------------------------------------
int __thiscall sub_100022C0(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x50u, *((_DWORD *)this - 1), UACTION_WaitForEvent::_UACTION_WaitForEvent);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    UACTION_WaitForEvent::_UACTION_WaitForEvent(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 80);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10002320) --------------------------------------------------------
int __thiscall UACTION_EnableAIVoice::execInitActionFor(void *this, int a2, int a3)
{
  int v3; // eax@1
  int v4; // edx@1
  void *v5; // edi@1
  int v6; // edx@1
  int v7; // ecx@2
  int result; // eax@3
  void *v9; // [sp+0h] [bp-4h]@1

  v9 = this;
  v3 = *(_DWORD *)(a2 + 12);
  v9 = 0;
  v4 = *(_BYTE *)v3;
  *(_DWORD *)(a2 + 12) = v3 + 1;
  v5 = this;
  ((void (__thiscall *)(_DWORD, int, void **))*(&GNatives + v4))(*(_DWORD *)(a2 + 8), a2, &v9);
  v6 = *(_DWORD *)(a2 + 12) + 1;
  *(_DWORD *)(a2 + 12) = v6;
  if ( *(_BYTE *)v6 == 66 )
  {
    v7 = *(_DWORD *)(a2 + 8);
    *(_DWORD *)(a2 + 12) = v6 + 1;
    ((void (__thiscall *)(int, int, _DWORD))*(&GNatives + 66))(v7, a2, 0);
  }
  result = (int)GEngine;
  if ( *((_DWORD *)GEngine + 19) )
    result = UAudioSubsystem::DisableVoiceCuesManually(~(unsigned __int8)*((_DWORD *)v5 + 16) & 1);
  return result;
}
// 100050AC: using guessed type void *GNatives;
// 100052F8: using guessed type int __stdcall UAudioSubsystem__DisableVoiceCuesManually(_DWORD);
// 100052FC: using guessed type void *GEngine;

//----- (10002550) --------------------------------------------------------
void *__thiscall AScriptedController::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = AScriptedController::AScriptedController(this);
  return result;
}

//----- (10002560) --------------------------------------------------------
void *__thiscall UScriptedAction::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = UScriptedAction::UScriptedAction(this);
  return result;
}

//----- (10002570) --------------------------------------------------------
void *__thiscall UACTION_EnableAIVoice::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = UACTION_EnableAIVoice::UACTION_EnableAIVoice(this);
  return result;
}

//----- (10002580) --------------------------------------------------------
void *__thiscall UACTION_SetViewTarget::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = UACTION_SetViewTarget::UACTION_SetViewTarget(this);
  return result;
}

//----- (10002590) --------------------------------------------------------
void *__thiscall UACTION_TriggerEvent::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = UACTION_TriggerEvent::UACTION_TriggerEvent(this);
  return result;
}

//----- (100025A0) --------------------------------------------------------
void *__thiscall ULatentScriptedAction::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = ULatentScriptedAction::ULatentScriptedAction(this);
  return result;
}

//----- (100025B0) --------------------------------------------------------
void *__thiscall UACTION_TeleportToPoint::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = UACTION_TeleportToPoint::UACTION_TeleportToPoint(this);
  return result;
}

//----- (100025C0) --------------------------------------------------------
void *__thiscall UACTION_WaitForEvent::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = UACTION_WaitForEvent::UACTION_WaitForEvent(this);
  return result;
}

//----- (100025D0) --------------------------------------------------------
char __thiscall AScriptedSequence::RenderEditorSelected(void *this, int a2, int a3, int a4)
{
  void *v4; // edi@1
  char result; // al@1
  void *v6; // edi@2
  int i; // eax@2
  int v8; // esi@4
  int v9; // ebx@4
  int j; // eax@5
  int v11; // edx@10
  int v12; // eax@11
  int v13; // ecx@13
  int k; // eax@14
  int l; // eax@21
  int v16; // edx@26
  int v17; // eax@27
  int v18; // ecx@29
  int m; // eax@30
  int v20; // [sp+0h] [bp-48h]@1
  char v21; // [sp+Ch] [bp-3Ch]@2
  void *v22; // [sp+34h] [bp-14h]@1
  int *v23; // [sp+38h] [bp-10h]@1
  int v24; // [sp+44h] [bp-4h]@1
  int v25; // [sp+58h] [bp+10h]@3

  v23 = &v20;
  v4 = this;
  v22 = this;
  v24 = 0;
  AActor::RenderEditorSelected(a2, a3, a4);
  result = *((_BYTE *)v4 + 652);
  if ( result & 1 )
  {
    FLineBatcher::FLineBatcher(&v21, a3, 0);
    v6 = AActor::PrivateStaticClass;
    LOBYTE(v24) = 1;
    for ( i = 0; ; i = v25 + 1 )
    {
      v25 = i;
      if ( i >= 8 * *((_DWORD *)v22 + 165) >> 3 )
        break;
      v8 = *(_DWORD *)(*((_DWORD *)v22 + 164) + 4 * i);
      v9 = 0;
      if ( v8 )
      {
        for ( j = *(_DWORD *)(v8 + 36); j; j = *(_DWORD *)(j + 48) )
        {
          if ( (_UNKNOWN *)j == &UACTION_TeleportToPoint::PrivateStaticClass )
          {
            if ( *(_DWORD *)(v8 + 68) )
            {
              v11 = 0;
              while ( 1 )
              {
                v12 = *((_DWORD *)v22 + 38);
                if ( v11 >= 8 * *(_DWORD *)(v12 + 52) >> 3 )
                  goto LABEL_37;
                if ( v9 )
                  goto LABEL_38;
                v13 = *(_DWORD *)(*(_DWORD *)(v12 + 48) + 4 * v11++);
                if ( v13 )
                {
                  for ( k = *(_DWORD *)(v13 + 36); k; k = *(_DWORD *)(k + 48) )
                  {
                    if ( (void *)k == v6 )
                      goto LABEL_19;
                  }
                  if ( v6 )
                    continue;
LABEL_19:
                  if ( *(_DWORD *)(v13 + 184) == *(_DWORD *)(v8 + 68) )
                    v9 = v13;
                }
              }
            }
            break;
          }
        }
        for ( l = *(_DWORD *)(v8 + 36); l; l = *(_DWORD *)(l + 48) )
        {
          if ( (_UNKNOWN *)l == &UACTION_SetViewTarget::PrivateStaticClass )
          {
            if ( *(_DWORD *)(v8 + 64) )
            {
              v16 = 0;
              while ( 1 )
              {
                v17 = *((_DWORD *)v22 + 38);
                if ( v16 >= 8 * *(_DWORD *)(v17 + 52) >> 3 )
                  break;
                if ( v9 )
                  goto LABEL_38;
                v18 = *(_DWORD *)(*(_DWORD *)(v17 + 48) + 4 * v16++);
                if ( v18 )
                {
                  for ( m = *(_DWORD *)(v18 + 36); m; m = *(_DWORD *)(m + 48) )
                  {
                    if ( (void *)m == v6 )
                      goto LABEL_35;
                  }
                  if ( v6 )
                    continue;
LABEL_35:
                  if ( *(_DWORD *)(v18 + 184) == *(_DWORD *)(v8 + 64) )
                    v9 = v18;
                }
              }
            }
            break;
          }
        }
LABEL_37:
        if ( v9 )
        {
LABEL_38:
          FLineBatcher::DrawLine(&v21, (char *)v22 + 312, v9 + 312, *(_DWORD *)(v8 + 52));
          v6 = AActor::PrivateStaticClass;
        }
      }
    }
    LOBYTE(v24) = 0;
    result = FLineBatcher::_FLineBatcher(&v21);
  }
  return result;
}
// 100051F0: using guessed type int __stdcall AActor__RenderEditorSelected(_DWORD, _DWORD, _DWORD);
// 10005300: using guessed type int __thiscall FLineBatcher___FLineBatcher(_DWORD);
// 10005304: using guessed type int __thiscall FLineBatcher__DrawLine(_DWORD, _DWORD, _DWORD, _DWORD);
// 10005308: using guessed type void *AActor__PrivateStaticClass;
// 1000530C: using guessed type int __thiscall FLineBatcher__FLineBatcher(_DWORD, _DWORD, _DWORD);

//----- (10002860) --------------------------------------------------------
void *__thiscall sub_10002860(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // ecx@2
  int v4; // eax@6
  int v5; // edx@7
  int v6; // eax@8
  void *result; // eax@11

  v2 = this;
  *(_DWORD *)this = a2;
  if ( a2 )
    v3 = *(_DWORD *)(a2 + 60);
  else
    v3 = 0;
  *((_DWORD *)v2 + 1) = v3;
  if ( a2 )
  {
    while ( !*((_DWORD *)v2 + 1) )
    {
LABEL_8:
      v6 = (*(int (**)(void))(**(_DWORD **)v2 + 140))();
      *(_DWORD *)v2 = v6;
      if ( v6 )
        *((_DWORD *)v2 + 1) = *(_DWORD *)(v6 + 60);
      if ( !*(_DWORD *)v2 )
        goto LABEL_11;
    }
    while ( 1 )
    {
      v4 = *((_DWORD *)v2 + 1);
      if ( *(_DWORD *)(*(_DWORD *)(v4 + 36) + 148) & 0x8000 )
        break;
      v5 = *(_DWORD *)(v4 + 40);
      *((_DWORD *)v2 + 1) = v5;
      if ( !v5 )
        goto LABEL_8;
    }
LABEL_11:
    result = v2;
  }
  else
  {
    result = v2;
  }
  return result;
}

//----- (10002940) --------------------------------------------------------
int __thiscall sub_10002940(int this, int a2, int a3)
{
  int v3; // edi@1
  int v4; // edx@1
  bool v5; // zf@1
  int v6; // ecx@2
  int v7; // ebx@3
  int v8; // eax@3
  int v9; // eax@7
  int v10; // eax@10
  void *v11; // eax@13
  int v12; // ecx@14
  int result; // eax@19
  int v14; // [sp+0h] [bp-28h]@1
  int v15; // [sp+14h] [bp-14h]@1
  int *v16; // [sp+18h] [bp-10h]@1
  int v17; // [sp+24h] [bp-4h]@1

  v3 = this;
  v4 = *(_DWORD *)this;
  v5 = *(_DWORD *)this == 0;
  v16 = &v14;
  v15 = this;
  v17 = 0;
  if ( v5 || (v6 = *(_DWORD *)(this + 4), v6 & 0x20000000) )
  {
    v7 = a2;
    v10 = a3;
    if ( a2 + a3 )
    {
      if ( a2 >= a3 )
        v10 = a2;
      v11 = (void *)(*(int (__stdcall **)(int))(*(_DWORD *)GMalloc + 4))(4 * v10);
      if ( *(_DWORD *)v3 )
      {
        v12 = 8 * *(_DWORD *)(v3 + 4) >> 3;
        if ( v12 > a2 )
          v12 = a2;
        memcpy(v11, *(const void **)v3, 4 * v12);
        v3 = v15;
      }
      *(_DWORD *)v3 = v11;
    }
    else
    {
      *(_DWORD *)v3 = 0;
    }
  }
  else
  {
    v7 = a2;
    v8 = 8 * v6 >> 3;
    if ( a2 <= v8 )
    {
      if ( v6 >= 0 && ((4 * a2 + 31) & 0xFFFFFFE0u) < ((4 * v8 + 31) & 0xFFFFFFE0u) )
      {
        v9 = a3;
        if ( a3 < a2 )
          v9 = a2;
        *(_DWORD *)v3 = (*(int (__stdcall **)(_DWORD, int, int))(*(_DWORD *)GMalloc + 8))(*(_DWORD *)v3, 4 * a2, 4 * v9);
      }
    }
    else
    {
      *(_DWORD *)v3 = (*(int (__stdcall **)(int, int, int))(*(_DWORD *)GMalloc + 8))(v4, 4 * a2, 4 * a3);
    }
  }
  result = (v7 ^ *(_DWORD *)(v3 + 4)) & 0x1FFFFFFF ^ *(_DWORD *)(v3 + 4);
  *(_DWORD *)(v3 + 4) = result;
  return result;
}
// 10005000: using guessed type void *GMalloc;

//----- (10002AB0) --------------------------------------------------------
int __thiscall sub_10002AB0(int this, int a2, int a3)
{
  int result; // eax@1
  int v4; // esi@1
  int v5; // [sp+0h] [bp-20h]@1
  int *v6; // [sp+10h] [bp-10h]@1
  int v7; // [sp+1Ch] [bp-4h]@2

  result = 0;
  v6 = &v5;
  v4 = this;
  if ( a3 )
  {
    v7 = 0;
    while ( result < a3 )
      ++result;
    memmove(
      (void *)(*(_DWORD *)this + 4 * a2),
      (const void *)(*(_DWORD *)this + 4 * (a2 + a3)),
      4 * ((8 * *(_DWORD *)(this + 4) >> 3) - a2 - a3));
    result = sub_10002940(v4, (8 * *(_DWORD *)(v4 + 4) >> 3) - a3, 0);
  }
  return result;
}

//----- (10002B39) --------------------------------------------------------
void __usercall sub_10002B39(int a1<ebp>)
{
  *(_DWORD *)(a1 - 20) = *(_DWORD *)(a1 + 12);
  CxxThrowException(a1 - 20, &unk_10006020);
}
// 100037FC: using guessed type int __cdecl CxxThrowException(_DWORD, _DWORD);

//----- (10002B4D) --------------------------------------------------------
void __cdecl sub_10002B4D()
{
  appUnwindf("%s", off_1000B088);
  CxxThrowException(0, 0);
}
// 100037FC: using guessed type int __cdecl CxxThrowException(_DWORD, _DWORD);
// 100050B0: using guessed type void appUnwindf(const char *, ...);
// 1000B088: using guessed type char *off_1000B088;

//----- (10002BD0) --------------------------------------------------------
int __thiscall UScriptedAction::GetDescription(void *this, int a2)
{
  void *v2; // esi@1
  char v3; // al@1
  signed int v4; // ebp@1
  int v5; // eax@3
  bool v6; // zf@5
  int v7; // eax@5
  int v8; // eax@8
  int v9; // esi@14
  int v10; // ebp@15
  int v11; // edi@16
  int v12; // edx@18
  int v13; // eax@18
  int v14; // ecx@18
  int v15; // edx@19
  int v16; // ecx@27
  int v17; // eax@29
  char v19; // [sp+30h] [bp-124h]@1
  int v20; // [sp+38h] [bp-11Ch]@1
  int v21; // [sp+3Ch] [bp-118h]@1
  int v22; // [sp+40h] [bp-114h]@14
  int v23; // [sp+44h] [bp-110h]@14
  __int16 v24; // [sp+48h] [bp-10Ch]@12
  char v25; // [sp+4Ah] [bp-10Ah]@12
  char v26; // [sp+4Bh] [bp-109h]@12
  char v27; // [sp+147h] [bp-Dh]@12
  int v28; // [sp+150h] [bp-4h]@1

  v2 = this;
  v20 = (int)this;
  v21 = 0;
  FString::FString(&v19);
  v3 = *((_BYTE *)v2 + 48);
  v4 = 1;
  v28 = 1;
  if ( v3 & 2 )
    FString::operator_(&v19, "// ");
  v5 = *(_DWORD *)(*((_DWORD *)v2 + 9) + 32);
  if ( !v5 )
    v5 = *(_DWORD *)FName::Names;
  v6 = appStrnicmp((const char *)(v5 + 12), "ACTION_", 7) == 0;
  v7 = *(_DWORD *)(*((_DWORD *)v2 + 9) + 32);
  if ( v6 )
  {
    if ( !v7 )
      v7 = *(_DWORD *)FName::Names;
    v8 = v7 + 19;
  }
  else
  {
    if ( !v7 )
      v7 = *(_DWORD *)FName::Names;
    v8 = v7 + 12;
  }
  FString::operator__(&v19, v8);
  v24 = word_100059C0;
  v25 = byte_100059C2;
  memset(&v26, 0, 0xFCu);
  v27 = 0;
  if ( !(dword_1000B0E4 & 1) )
  {
    dword_1000B0E4 |= 1u;
    LOBYTE(v28) = 2;
    FName::FName(&dword_1000B0E0, "bDisabled", 2);
    LOBYTE(v28) = 1;
  }
  sub_10002860(&v22, *((_DWORD *)v2 + 9));
  v9 = v23;
  if ( v23 )
  {
    v10 = v22;
    do
    {
      v11 = *(_DWORD *)(v9 + 48);
      if ( v11 && *(_DWORD *)(v9 + 32) != dword_1000B0E0 )
      {
        v12 = *(_DWORD *)(v20 + 36);
        v13 = 8 * *(_DWORD *)(v12 + 232) >> 3;
        v14 = 0;
        if ( v13 <= 0 )
          goto LABEL_24;
        v15 = *(_DWORD *)(v12 + 228);
        while ( *(_DWORD *)v15 != v11 )
        {
          ++v14;
          v15 += 4;
          if ( v14 >= v13 )
            goto LABEL_24;
        }
        if ( v14 == -1 )
        {
LABEL_24:
          (*(void (__thiscall **)(int, _DWORD, char *, int, int, signed int))(*(_DWORD *)v9 + 188))(
            v9,
            0,
            &v25,
            v20,
            v20,
            11);
          FString::operator__(&v19, &v24);
          LOBYTE(v24) = 44;
        }
      }
      v9 = *(_DWORD *)(v9 + 40);
      if ( v10 )
      {
        while ( !v9 )
        {
LABEL_29:
          v17 = (*(int (__thiscall **)(int))(*(_DWORD *)v10 + 140))(v10);
          v10 = v17;
          if ( !v17 )
            goto LABEL_31;
          v9 = *(_DWORD *)(v17 + 60);
        }
        while ( 1 )
        {
          v16 = *(_DWORD *)(*(_DWORD *)(v9 + 36) + 148);
          if ( SBYTE1(v16) < 0 )
            break;
          v9 = *(_DWORD *)(v9 + 40);
          if ( !v9 )
            goto LABEL_29;
        }
      }
LABEL_31:
      ;
    }
    while ( v9 );
    v4 = 1;
  }
  FString::FString(a2, &v19);
  v21 = v4;
  LOBYTE(v28) = 0;
  FString::_FString(&v19);
  return a2;
}
// 1000504C: using guessed type int __thiscall FName__FName(_DWORD, _DWORD, _DWORD);
// 100050B4: using guessed type int __thiscall FString___FString(_DWORD);
// 100050B8: using guessed type int __thiscall FString__FString(_DWORD, _DWORD);
// 100050BC: using guessed type int __thiscall FString__operator__(_DWORD, _DWORD);
// 100050C0: using guessed type int __fastcall appStrnicmp(const char *, const char *, int);
// 100050C4: using guessed type void *FName__Names;
// 100050C8: using guessed type int __thiscall FString__operator_(_DWORD, _DWORD);
// 100050CC: using guessed type int __thiscall FString__FString(_DWORD);
// 100059C0: using guessed type __int16 word_100059C0;
// 100059C2: using guessed type char byte_100059C2;
// 1000B0E0: using guessed type int dword_1000B0E0;
// 1000B0E4: using guessed type int dword_1000B0E4;

//----- (10002E10) --------------------------------------------------------
int __thiscall sub_10002E10(int this, int a2)
{
  int v2; // esi@1
  int result; // eax@1
  int v4; // ecx@1

  v2 = this;
  sub_10002940(this, 0, 0);
  result = a2;
  *(_DWORD *)v2 = *(_DWORD *)a2;
  v4 = (*(_DWORD *)(v2 + 4) ^ (8 * *(_DWORD *)(a2 + 4) >> 3)) & 0x1FFFFFFF ^ *(_DWORD *)(v2 + 4);
  *(_DWORD *)(v2 + 4) = v4;
  *(_DWORD *)(v2 + 4) = v4 ^ (v4 ^ (4 * *(_DWORD *)(a2 + 4) >> 2)) & 0x20000000;
  *(_DWORD *)(result + 4) |= 0x20000000u;
  return result;
}

//----- (10002E60) --------------------------------------------------------
int __thiscall sub_10002E60(int this, int a2, int a3)
{
  int v3; // edi@1
  int v4; // esi@1
  int result; // eax@2
  int v6; // ecx@4
  void *v7; // edi@5
  unsigned int v8; // edx@5
  int v9; // edi@5
  int i; // ecx@5

  v3 = this;
  v4 = 8 * *(_DWORD *)(this + 4) >> 3;
  if ( a2 >= v4 )
    result = sub_10002940(this, a2, a3);
  else
    result = sub_10002AB0(this, a2, (8 * *(_DWORD *)(this + 4) >> 3) - a2);
  v6 = 8 * *(_DWORD *)(v3 + 4) >> 3;
  if ( v6 > v4 )
  {
    v7 = (void *)(*(_DWORD *)v3 + 4 * v4);
    v8 = 4 * (v6 - v4);
    result = 0;
    memset(v7, 0, 4 * (v8 >> 2));
    v9 = (int)((char *)v7 + 4 * (v8 >> 2));
    for ( i = 0; i; --i )
      *(_BYTE *)v9++ = 0;
  }
  return result;
}

//----- (10002ED0) --------------------------------------------------------
int __thiscall AScriptedSequence::_AScriptedSequence(void *this)
{
  void *v1; // esi@1
  int v2; // eax@4

  v1 = this;
  *(_DWORD *)this = &AScriptedSequence::_vftable_;
  UObject::ConditionalDestroy();
  if ( !(*((_DWORD *)v1 + 165) & 0x20000000) && *((_DWORD *)v1 + 164) )
    (*(void (__stdcall **)(_DWORD))(*(_DWORD *)GMalloc + 12))(*((_DWORD *)v1 + 164));
  v2 = *((_DWORD *)v1 + 165) & 0xE0000000;
  *((_DWORD *)v1 + 164) = 0;
  *((_DWORD *)v1 + 165) = v2;
  return AAIScript::_AAIScript(v1);
}
// 10005000: using guessed type void *GMalloc;
// 10005040: using guessed type int UObject__ConditionalDestroy(void);
// 10005320: using guessed type int __thiscall AAIScript___AAIScript(_DWORD);
// 100059D0: using guessed type int (__thiscall *AScriptedSequence___vftable_)(void *, char);

//----- (10002F70) --------------------------------------------------------
void *__thiscall AScriptedSequence::AScriptedSequence(void *this)
{
  void *v1; // esi@1

  v1 = this;
  AAIScript::AAIScript();
  *(_DWORD *)v1 = &AScriptedSequence::_vftable_;
  return v1;
}
// 10005324: using guessed type int AAIScript__AAIScript(void);
// 100059D0: using guessed type int (__thiscall *AScriptedSequence___vftable_)(void *, char);

//----- (10002FC0) --------------------------------------------------------
int __thiscall sub_10002FC0(void *this, char a2)
{
  void *v2; // esi@1
  int result; // eax@4

  v2 = this;
  if ( a2 & 2 )
  {
    unknown_libname_1(this, 0x29Cu, *((_DWORD *)this - 1), AScriptedSequence::_AScriptedSequence);
    if ( a2 & 1 )
      (*(void (__stdcall **)(char *))(*(_DWORD *)GMalloc + 12))((char *)v2 - 4);
    result = (int)((char *)v2 - 4);
  }
  else
  {
    AScriptedSequence::_AScriptedSequence(this);
    if ( a2 & 1 )
      UObject::operator delete(v2, 668);
    result = (int)v2;
  }
  return result;
}
// 10005000: using guessed type void *GMalloc;
// 10005044: using guessed type int __fastcall UObject__operator delete(_DWORD, _DWORD);

//----- (10003030) --------------------------------------------------------
void *__thiscall AScriptedSequence::InternalConstructor(void *this)
{
  void *result; // eax@2

  if ( this )
    result = AScriptedSequence::AScriptedSequence(this);
  return result;
}

//----- (10003040) --------------------------------------------------------
int __thiscall sub_10003040(int this, int a2)
{
  int v2; // esi@1
  int v3; // eax@2
  int v4; // eax@3

  v2 = this;
  if ( this == a2 )
    return v2;
  v3 = *(_DWORD *)(a2 + 4);
  if ( v3 & 0x60000000 )
  {
    sub_10002E10(this, a2);
    return v2;
  }
  sub_10002E60(this, 8 * v3 >> 3, 8 * v3 >> 3);
  v4 = 0;
  if ( 8 * *(_DWORD *)(v2 + 4) <= 0 )
    return v2;
  do
  {
    *(_DWORD *)(*(_DWORD *)v2 + 4 * v4) = *(_DWORD *)(*(_DWORD *)a2 + 4 * v4);
    ++v4;
  }
  while ( v4 < 8 * *(_DWORD *)(v2 + 4) >> 3 );
  return v2;
}

//----- (100030F0) --------------------------------------------------------
void *__thiscall AScriptedSequence::operator_(void *this, int a2)
{
  void *v2; // esi@1

  v2 = this;
  AAIScript::operator_(a2);
  *((_DWORD *)v2 + 163) ^= ((unsigned __int8)*((_DWORD *)v2 + 163) ^ (unsigned __int8)*(_DWORD *)(a2 + 652)) & 1;
  sub_10003040((int)((char *)v2 + 656), a2 + 656);
  *((_DWORD *)v2 + 166) = *(_DWORD *)(a2 + 664);
  return v2;
}
// 10005328: using guessed type int __stdcall AAIScript__operator_(_DWORD);

//----- (10003160) --------------------------------------------------------
void *__thiscall AScriptedSequence::AScriptedSequence(void *this, int a2)
{
  void *v2; // esi@1
  int v3; // edx@1

  v2 = this;
  AAIScript::AAIScript(a2);
  v3 = *((_DWORD *)v2 + 163);
  *(_DWORD *)v2 = &AScriptedSequence::_vftable_;
  *((_DWORD *)v2 + 163) = ((unsigned __int8)v3 ^ (unsigned __int8)*(_DWORD *)(a2 + 652)) & 1 ^ v3;
  *((_DWORD *)v2 + 164) = 0;
  *((_DWORD *)v2 + 165) = 0;
  sub_10003040((int)((char *)v2 + 656), a2 + 656);
  *((_DWORD *)v2 + 166) = *(_DWORD *)(a2 + 664);
  return v2;
}
// 1000532C: using guessed type int __stdcall AAIScript__AAIScript(_DWORD);
// 100059D0: using guessed type int (__thiscall *AScriptedSequence___vftable_)(void *, char);

//----- (10003210) --------------------------------------------------------
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
  dword_1000B0E8 = (int)hinstDLL;
  return 1;
}
// 1000B0E8: using guessed type int dword_1000B0E8;

//----- (10003A4E) --------------------------------------------------------
void __cdecl sub_10003A4E()
{
  unsigned int i; // [sp+Ch] [bp-1Ch]@1

  for ( i = (unsigned int)&unk_10005E00; i < (unsigned int)&unk_10005E00; i += 4 )
  {
    if ( *(_DWORD *)i )
      (*(void (**)(void))i)();
  }
}

//----- (10003A92) --------------------------------------------------------
void __cdecl sub_10003A92()
{
  unsigned int i; // [sp+Ch] [bp-1Ch]@1

  for ( i = (unsigned int)&unk_10005E08; i < (unsigned int)&unk_10005E08; i += 4 )
  {
    if ( *(_DWORD *)i )
      (*(void (**)(void))i)();
  }
}

//----- (10003AF0) --------------------------------------------------------
int __usercall sub_10003AF0<eax>(int a1<ebp>)
{
  return AAIController::_AAIController(*(_DWORD *)(a1 - 16));
}
// 100052E8: using guessed type int __thiscall AAIController___AAIController(_DWORD);

//----- (10003AF9) --------------------------------------------------------
int __cdecl AScriptedController::_AScriptedController()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003B10) --------------------------------------------------------
int __cdecl sub_10003B10()
{
  int result; // eax@1

  result = _local_static_guard_ & 0xFFFFFFFE;
  _local_static_guard_ &= 0xFFFFFFFEu;
  return result;
}
// 1000B0D4: using guessed type int _local static guard_;

//----- (10003B1E) --------------------------------------------------------
int __cdecl UScriptedAction::InitActionFor()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003B30) --------------------------------------------------------
int __cdecl sub_10003B30()
{
  int result; // eax@1

  result = _local_static_guard_ & 0xFFFFFFFE;
  _local_static_guard_ &= 0xFFFFFFFEu;
  return result;
}
// 1000B0DC: using guessed type int _local static guard_;

//----- (10003B3E) --------------------------------------------------------
int __cdecl UScriptedAction::GetActionActor()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003B50) --------------------------------------------------------
int __usercall sub_10003B50<eax>(int a1<ebp>)
{
  return UObject::_UObject(*(_DWORD *)(a1 - 16));
}
// 1000508C: using guessed type int __thiscall UObject___UObject(_DWORD);

//----- (10003B59) --------------------------------------------------------
int __usercall sub_10003B59<eax>(int a1<ebp>)
{
  return FStringNoInit::_FStringNoInit(*(_DWORD *)(a1 - 16) + 40);
}
// 10005090: using guessed type int __thiscall FStringNoInit___FStringNoInit(_DWORD);

//----- (10003B65) --------------------------------------------------------
int __usercall sub_10003B65<eax>(int a1<ebp>)
{
  return FStringNoInit::_FStringNoInit(*(_DWORD *)(a1 - 16) + 56);
}
// 10005090: using guessed type int __thiscall FStringNoInit___FStringNoInit(_DWORD);

//----- (10003B71) --------------------------------------------------------
int __cdecl UScriptedAction::_UScriptedAction()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003B80) --------------------------------------------------------
int __usercall sub_10003B80<eax>(int a1<ebp>)
{
  return UObject::_UObject(*(_DWORD *)(a1 - 16));
}
// 1000508C: using guessed type int __thiscall UObject___UObject(_DWORD);

//----- (10003B89) --------------------------------------------------------
int __usercall sub_10003B89<eax>(int a1<ebp>)
{
  return FStringNoInit::_FStringNoInit(*(_DWORD *)(a1 - 16) + 40);
}
// 10005090: using guessed type int __thiscall FStringNoInit___FStringNoInit(_DWORD);

//----- (10003B95) --------------------------------------------------------
int __cdecl UScriptedAction::UScriptedAction()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003BA0) --------------------------------------------------------
int __usercall sub_10003BA0<eax>(int a1<ebp>)
{
  return UObject::_UObject(*(_DWORD *)(a1 - 16));
}
// 1000508C: using guessed type int __thiscall UObject___UObject(_DWORD);

//----- (10003BA9) --------------------------------------------------------
int __usercall sub_10003BA9<eax>(int a1<ebp>)
{
  return FStringNoInit::_FStringNoInit(*(_DWORD *)(a1 - 16) + 40);
}
// 10005090: using guessed type int __thiscall FStringNoInit___FStringNoInit(_DWORD);

//----- (10003BB5) --------------------------------------------------------
int __cdecl UScriptedAction::UScriptedAction()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003BC0) --------------------------------------------------------
int __usercall sub_10003BC0<eax>(int a1<ebp>)
{
  return UScriptedAction::_UScriptedAction(*(void **)(a1 - 16));
}

//----- (10003BC8) --------------------------------------------------------
int __cdecl UACTION_EnableAIVoice::_UACTION_EnableAIVoice()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003BE0) --------------------------------------------------------
int __usercall sub_10003BE0<eax>(int a1<ebp>)
{
  return UScriptedAction::_UScriptedAction(*(void **)(a1 - 16));
}

//----- (10003BE8) --------------------------------------------------------
int __cdecl UACTION_SetViewTarget::_UACTION_SetViewTarget()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003C00) --------------------------------------------------------
int __usercall sub_10003C00<eax>(int a1<ebp>)
{
  return UScriptedAction::_UScriptedAction(*(void **)(a1 - 16));
}

//----- (10003C08) --------------------------------------------------------
int __cdecl UACTION_TriggerEvent::_UACTION_TriggerEvent()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003C20) --------------------------------------------------------
int __usercall sub_10003C20<eax>(int a1<ebp>)
{
  return UScriptedAction::_UScriptedAction(*(void **)(a1 - 16));
}

//----- (10003C28) --------------------------------------------------------
int __cdecl ULatentScriptedAction::_ULatentScriptedAction()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003C40) --------------------------------------------------------
int __usercall sub_10003C40<eax>(int a1<ebp>)
{
  return ULatentScriptedAction::_ULatentScriptedAction(*(void **)(a1 - 16));
}

//----- (10003C48) --------------------------------------------------------
int __cdecl UACTION_TeleportToPoint::_UACTION_TeleportToPoint()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003C60) --------------------------------------------------------
int __usercall sub_10003C60<eax>(int a1<ebp>)
{
  return ULatentScriptedAction::_ULatentScriptedAction(*(void **)(a1 - 16));
}

//----- (10003C68) --------------------------------------------------------
int __cdecl UACTION_WaitForEvent::_UACTION_WaitForEvent()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003C80) --------------------------------------------------------
int __usercall sub_10003C80<eax>(int a1<ebp>)
{
  return FLineBatcher::_FLineBatcher(a1 - 60);
}
// 10005300: using guessed type int __thiscall FLineBatcher___FLineBatcher(_DWORD);

//----- (10003C89) --------------------------------------------------------
int __cdecl AScriptedSequence::RenderEditorSelected()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003CA0) --------------------------------------------------------
int __cdecl SEH_10002940()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003CB0) --------------------------------------------------------
int __cdecl SEH_10002AB0()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003CC0) --------------------------------------------------------
int __usercall sub_10003CC0<eax>(int a1<ebp>)
{
  return FString::_FString(a1 - 292);
}
// 100050B4: using guessed type int __thiscall FString___FString(_DWORD);

//----- (10003CCC) --------------------------------------------------------
int __cdecl sub_10003CCC()
{
  int result; // eax@1

  result = dword_1000B0E4 & 0xFFFFFFFE;
  dword_1000B0E4 &= 0xFFFFFFFEu;
  return result;
}
// 1000B0E4: using guessed type int dword_1000B0E4;

//----- (10003CDA) --------------------------------------------------------
int __usercall sub_10003CDA<eax>(int a1<ebp>)
{
  int result; // eax@1

  result = *(_DWORD *)(a1 - 280) & 1;
  if ( *(_DWORD *)(a1 - 280) & 1 )
  {
    *(_DWORD *)(a1 - 280) &= 0xFFFFFFFEu;
    result = FString::_FString(*(_DWORD *)(a1 + 4));
  }
  return result;
}
// 100050B4: using guessed type int __thiscall FString___FString(_DWORD);

//----- (10003CFA) --------------------------------------------------------
int __cdecl UScriptedAction::GetDescription()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003D10) --------------------------------------------------------
int __usercall sub_10003D10<eax>(int a1<ebp>)
{
  return AAIScript::_AAIScript(*(_DWORD *)(a1 - 16));
}
// 10005320: using guessed type int __thiscall AAIScript___AAIScript(_DWORD);

//----- (10003D19) --------------------------------------------------------
int __usercall sub_10003D19<eax>(int a1<ebp>)
{
  int v1; // esi@1
  int result; // eax@4

  v1 = *(_DWORD *)(a1 - 16) + 656;
  if ( !(*(_DWORD *)(*(_DWORD *)(a1 - 16) + 660) & 0x20000000) && *(_DWORD *)(*(_DWORD *)(a1 - 16) + 656) )
    (*(void (__stdcall **)(_DWORD))(*(_DWORD *)GMalloc + 12))(*(_DWORD *)v1);
  result = *(_DWORD *)(v1 + 4) & 0xE0000000;
  *(_DWORD *)v1 = 0;
  *(_DWORD *)(v1 + 4) = result;
  return result;
}
// 10005000: using guessed type void *GMalloc;

//----- (10003D27) --------------------------------------------------------
int __cdecl AScriptedSequence::_AScriptedSequence()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003D40) --------------------------------------------------------
int __usercall sub_10003D40<eax>(int a1<ebp>)
{
  return AAIScript::_AAIScript(*(_DWORD *)(a1 - 16));
}
// 10005320: using guessed type int __thiscall AAIScript___AAIScript(_DWORD);

//----- (10003D49) --------------------------------------------------------
int __cdecl AScriptedSequence::AScriptedSequence()
{
  return _CxxFrameHandler();
}
// 100036C0: using guessed type int _CxxFrameHandler(void);

//----- (10003D60) --------------------------------------------------------
int __cdecl sub_10003D60(int a1, int a2)
{
  int v2; // eax@1
  void *v4; // [sp+10h] [bp-8h]@1
  void *v5; // [sp+14h] [bp-4h]@1

  v4 = UObject::PrivateStaticClass;
  v5 = AAIScript::PrivateStaticClass;
  v2 = UObject::StaticConfigName(67649540, AScriptedSequence::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &AScriptedSequence::PrivateStaticClass,
    0,
    668,
    0,
    a2,
    a1,
    0,
    0,
    0,
    0,
    "ScriptedSequence",
    "Gameplay",
    v2);
  return atexit(sub_100042B0);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050DC: using guessed type void *UObject__PrivateStaticClass;
// 100050E0: using guessed type void *UObject__StaticConstructor;
// 10005330: using guessed type void *AAIScript__PrivateStaticClass;

//----- (10003DF0) --------------------------------------------------------
void __cdecl sub_10003DF0()
{
  autoclassAScriptedSequence = (int)&AScriptedSequence::PrivateStaticClass;
}
// 1000B210: using guessed type int autoclassAScriptedSequence;

//----- (10003E00) --------------------------------------------------------
int __cdecl sub_10003E00(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, AScriptedController::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &AScriptedController::PrivateStaticClass,
    0,
    920,
    4,
    a2,
    a1,
    0,
    0,
    0,
    0,
    "ScriptedController",
    "Gameplay",
    v2);
  return atexit(sub_100042C0);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (10003E90) --------------------------------------------------------
void __cdecl sub_10003E90()
{
  autoclassAScriptedController = (int)&AScriptedController::PrivateStaticClass;
}
// 1000BADC: using guessed type int autoclassAScriptedController;

//----- (10003EA0) --------------------------------------------------------
int __cdecl sub_10003EA0(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, UScriptedAction::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(&UScriptedAction::PrivateStaticClass, 0, 64, 0, a2, a1, 0, 0, 0, 0, "ScriptedAction", "Gameplay", v2);
  return atexit(sub_100042D0);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (10003F20) --------------------------------------------------------
void __cdecl sub_10003F20()
{
  autoclassUScriptedAction = (int)&UScriptedAction::PrivateStaticClass;
}
// 1000B0F0: using guessed type int autoclassUScriptedAction;

//----- (10003F30) --------------------------------------------------------
int __cdecl sub_10003F30(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, UACTION_EnableAIVoice::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &UACTION_EnableAIVoice::PrivateStaticClass,
    0,
    68,
    0,
    &UScriptedAction::PrivateStaticClass,
    a2,
    0,
    0,
    0,
    0,
    "ACTION_EnableAIVoice",
    "Gameplay",
    v2);
  return atexit(sub_100042E0);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (10003FB0) --------------------------------------------------------
void __cdecl sub_10003FB0()
{
  autoclassUACTION_EnableAIVoice = (int)&UACTION_EnableAIVoice::PrivateStaticClass;
}
// 1000B8A8: using guessed type int autoclassUACTION_EnableAIVoice;

//----- (10003FC0) --------------------------------------------------------
int __cdecl sub_10003FC0()
{
  dword_1000B88C = (int)&UACTION_EnableAIVoice::StaticNativeMap;
  return UClass::RegisterNatives(&UACTION_EnableAIVoice::PrivateStaticClass);
}
// 100050D0: using guessed type int __thiscall UClass__RegisterNatives(_DWORD);
// 1000B098: using guessed type char *UACTION_EnableAIVoice__StaticNativeMap;
// 1000B88C: using guessed type int dword_1000B88C;

//----- (10003FE0) --------------------------------------------------------
int __cdecl sub_10003FE0(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, UACTION_SetViewTarget::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &UACTION_SetViewTarget::PrivateStaticClass,
    0,
    68,
    0,
    &UScriptedAction::PrivateStaticClass,
    a2,
    0,
    0,
    0,
    0,
    "ACTION_SetViewTarget",
    "Gameplay",
    v2);
  return atexit(sub_100042F0);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (10004060) --------------------------------------------------------
void __cdecl sub_10004060()
{
  autoclassUACTION_SetViewTarget = (int)&UACTION_SetViewTarget::PrivateStaticClass;
}
// 1000B20C: using guessed type int autoclassUACTION_SetViewTarget;

//----- (10004070) --------------------------------------------------------
int __cdecl sub_10004070(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, UACTION_TriggerEvent::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &UACTION_TriggerEvent::PrivateStaticClass,
    0,
    68,
    0,
    &UScriptedAction::PrivateStaticClass,
    a2,
    0,
    0,
    0,
    0,
    "ACTION_TriggerEvent",
    "Gameplay",
    v2);
  return atexit(sub_10004300);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (100040F0) --------------------------------------------------------
void __cdecl sub_100040F0()
{
  autoclassUACTION_TriggerEvent = (int)&UACTION_TriggerEvent::PrivateStaticClass;
}
// 1000B55C: using guessed type int autoclassUACTION_TriggerEvent;

//----- (10004100) --------------------------------------------------------
int __cdecl sub_10004100(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, ULatentScriptedAction::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &ULatentScriptedAction::PrivateStaticClass,
    0,
    64,
    0,
    &UScriptedAction::PrivateStaticClass,
    a2,
    0,
    0,
    0,
    0,
    "LatentScriptedAction",
    "Gameplay",
    v2);
  return atexit(sub_10004310);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (10004180) --------------------------------------------------------
void __cdecl sub_10004180()
{
  autoclassULatentScriptedAction = (int)&ULatentScriptedAction::PrivateStaticClass;
}
// 1000B214: using guessed type int autoclassULatentScriptedAction;

//----- (10004190) --------------------------------------------------------
int __cdecl sub_10004190(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, UACTION_TeleportToPoint::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &UACTION_TeleportToPoint::PrivateStaticClass,
    0,
    80,
    0,
    &ULatentScriptedAction::PrivateStaticClass,
    a2,
    0,
    0,
    0,
    0,
    "ACTION_TeleportToPoint",
    "Gameplay",
    v2);
  return atexit(sub_10004320);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (10004210) --------------------------------------------------------
void __cdecl sub_10004210()
{
  autoclassUACTION_TeleportToPoint = (int)&UACTION_TeleportToPoint::PrivateStaticClass;
}
// 1000B8A4: using guessed type int autoclassUACTION_TeleportToPoint;

//----- (10004220) --------------------------------------------------------
int __cdecl sub_10004220(int a1, int a2)
{
  int v2; // eax@1

  v2 = UObject::StaticConfigName(67649540, UACTION_WaitForEvent::InternalConstructor, UObject::StaticConstructor);
  UClass::UClass(
    &UACTION_WaitForEvent::PrivateStaticClass,
    0,
    80,
    0,
    &ULatentScriptedAction::PrivateStaticClass,
    a2,
    0,
    0,
    0,
    0,
    "ACTION_WaitForEvent",
    "Gameplay",
    v2);
  return atexit(sub_10004330);
}
// 100050D4: using guessed type int __thiscall UClass__UClass(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 100050D8: using guessed type int __stdcall UObject__StaticConfigName(_DWORD, _DWORD, _DWORD);
// 100050E0: using guessed type void *UObject__StaticConstructor;

//----- (100042A0) --------------------------------------------------------
void __cdecl sub_100042A0()
{
  autoclassUACTION_WaitForEvent = (int)&UACTION_WaitForEvent::PrivateStaticClass;
}
// 1000B8AC: using guessed type int autoclassUACTION_WaitForEvent;

//----- (100042B0) --------------------------------------------------------
int __cdecl sub_100042B0()
{
  return UClass::_UClass(&AScriptedSequence::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (100042C0) --------------------------------------------------------
int __cdecl sub_100042C0()
{
  return UClass::_UClass(&AScriptedController::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (100042D0) --------------------------------------------------------
int __cdecl sub_100042D0()
{
  return UClass::_UClass(&UScriptedAction::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (100042E0) --------------------------------------------------------
int __cdecl sub_100042E0()
{
  return UClass::_UClass(&UACTION_EnableAIVoice::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (100042F0) --------------------------------------------------------
int __cdecl sub_100042F0()
{
  return UClass::_UClass(&UACTION_SetViewTarget::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (10004300) --------------------------------------------------------
int __cdecl sub_10004300()
{
  return UClass::_UClass(&UACTION_TriggerEvent::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (10004310) --------------------------------------------------------
int __cdecl sub_10004310()
{
  return UClass::_UClass(&ULatentScriptedAction::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (10004320) --------------------------------------------------------
int __cdecl sub_10004320()
{
  return UClass::_UClass(&UACTION_TeleportToPoint::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

//----- (10004330) --------------------------------------------------------
int __cdecl sub_10004330()
{
  return UClass::_UClass(&UACTION_WaitForEvent::PrivateStaticClass);
}
// 100050E4: using guessed type int __thiscall UClass___UClass(_DWORD);

// ALL OK, 176 function(s) have been successfully decompiled
