/*===========================================================================
	C++ class definitions exported from UnrealScript.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/

#ifndef GAMEPLAY_NATIVE_DEFS
#define GAMEPLAY_NATIVE_DEFS

#include "../../Engine/Inc/Engine.h"

#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef GAMEPLAY_API
#define GAMEPLAY_API DLL_IMPORT
LINK_LIB(Gameplay)
#endif

/*
 * ScriptedSequence
 */

class GAMEPLAY_API AScriptedSequence : public AAIScript{
public:
	BITFIELD bDrawLinks:1;
	TArrayNoInit<class UScriptedAction*> Actions;
	class UClass* ScriptControllerClass;

	DECLARE_CLASS(AScriptedSequence,AAIScript,0,Gameplay)
	void RenderEditorSelected(FLevelSceneNode* SceneNode,FRenderInterface* RI, FDynamicActor* FDA);
};

/*
 * ScriptedController
 */

class GAMEPLAY_API AScriptedController : public AAIController{
public:
	BITFIELD bBroken:1;
	BITFIELD bUseScriptFacing:1;
	BITFIELD bUnforceStateOnEvent:1;
	INT ActionNum;
	INT AnimsRemaining;
	class AScriptedSequence* SequenceScript;
	class ULatentScriptedAction* CurrentAction;
	class UACTION_PlayAnim* CurrentAnimation;
	FLOAT ScriptPriorityOnEvent;
	class AActor* ScriptedFocus;
	class APlayerController* MyPlayerController;
	INT NumShots;
	FName FiringMode;
	INT IterationCounter;
	INT IterationSectionStart;

	DECLARE_CLASS(AScriptedController,AAIController,CLASS_Config,Gameplay)
	NO_DEFAULT_CONSTRUCTOR(AScriptedController)
};

/*
 * ScriptedAction
 */

class GAMEPLAY_API UScriptedAction : public UObject{
public:
	FStringNoInit ActionString;
	BITFIELD bValidForTrigger:1;
	BITFIELD bDisabled:1;
	FColor ActionColor;
	FStringNoInit Comment;

	DECLARE_CLASS(UScriptedAction,UObject,0,Gameplay)
};

/*
 * ACTION_EnableAIVoice
 */

class GAMEPLAY_API UACTION_EnableAIVoice : public UScriptedAction{
public:
	BITFIELD bEnable:1;
	void execInitActionFor(FFrame& Stack, void* Result);

	DECLARE_CLASS(UACTION_EnableAIVoice,UScriptedAction,0,Gameplay)
	NO_DEFAULT_CONSTRUCTOR(UACTION_EnableAIVoice)
};

/*
 * ACTION_SetViewTarget
 */

class GAMEPLAY_API UACTION_SetViewTarget : public UScriptedAction{
public:
	FName ViewTargetTag;

	DECLARE_CLASS(UACTION_SetViewTarget,UScriptedAction,0,Gameplay)
	NO_DEFAULT_CONSTRUCTOR(UACTION_SetViewTarget)
};

/*
 * ACTION_TriggerEvent
 */

class GAMEPLAY_API UACTION_TriggerEvent : public UScriptedAction{
public:
	FName Event;

	DECLARE_CLASS(UACTION_TriggerEvent,UScriptedAction,0,Gameplay)
	NO_DEFAULT_CONSTRUCTOR(UACTION_TriggerEvent)
};

/*
 * LatentScriptedAction
 */

class GAMEPLAY_API ULatentScriptedAction : public UScriptedAction{
public:
	DECLARE_CLASS(ULatentScriptedAction,UScriptedAction,0,Gameplay)
	NO_DEFAULT_CONSTRUCTOR(ULatentScriptedAction)
};

/*
 * ACTION_TeleportToPoint
 */

class GAMEPLAY_API UACTION_TeleportToPoint : public ULatentScriptedAction{
public:
	FName ActorToTeleportTag;
	FName DestinationTag;
	BITFIELD bPlaySpawnEffect:1;
	BITFIELD bNoCheck:1;
	class AActor* Dest;

	DECLARE_CLASS(UACTION_TeleportToPoint,ULatentScriptedAction,0,Gameplay)
	NO_DEFAULT_CONSTRUCTOR(UACTION_TeleportToPoint)
};

/*
 * ACTION_WaitForEvent
 */

class GAMEPLAY_API UACTION_WaitForEvent : public ULatentScriptedAction{
public:
	FName ExternalEvent;
	class ATriggeredCondition* T;
	FLOAT ScriptPriorityOnTrigger;
	BITFIELD UnforceStateOnTrigger:1;

	DECLARE_CLASS(UACTION_WaitForEvent,ULatentScriptedAction,0,Gameplay)
	NO_DEFAULT_CONSTRUCTOR(UACTION_WaitForEvent)
};

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#endif // GAMEPLAY_NATIVE_DEFS
